// src/lib/components/sidebar/CollapseButton.svelte
<script lang="ts">
    import { 
        persistSidebarState,
        sidebarState,
        toggleCollapse
    } from '$lib/stores/sidebar.store.svelte';

   // Toggles the sidebar's collapsed state and persists it.
    function handleClick() {
        toggleCollapse();
        persistSidebarState();
    }
</script>

<button 
    type="button"
    class="collapse-button"
    class:collapsed={sidebarState.isCollapsed}
    aria-label = {sidebarState.isCollapsed ? 'Open sidebar' : 'Close sidebar'}
    aria-expanded = {!sidebarState.isCollapsed}
    onclick = {handleClick}
>
    {sidebarState.isCollapsed ? '»' : '«'}
</button>

<style>
    .collapse-button {
        position: absolute;
        top: 12px;
        right: 8px;
        width: 24px;
        height: 24px;
        border-radius: 50%;
        border: 1px solid #D6D2C4;
        background: white;
        box-shadow: 0 1px 3px rgba(0, 0, 0, 0.12);

        font-size: 1rem;
        line-height: 1;
        color: #373A36;
        cursor: pointer;

        display: flex;
        align-items: center;
        justify-content: center;

        z-index: 20;
        transition: transform 0.15s ease, background 0.15 ease;
    }

    .collapse-button:hover {
        background: #EDEBE5;
        transform: scale(1.0);
    }

    .collapse-button.collapsed {
        right: -32px;
    }
</style>

// client-next/src/lib/components/sidebar/CollapseButton.tsx
'use client';

import { useSidebarStore } from '@/lib/stores/sidebar.store';

// Toggles the sidebar's collapsed state and persists it. Port of CollapseButton.svelte.
export default function CollapseButton() {
  const isCollapsed = useSidebarStore((s) => s.isCollapsed);
  const toggleCollapse = useSidebarStore((s) => s.toggleCollapse);
  const persist = useSidebarStore((s) => s.persist);

  return (
    <button
      type="button"
      className={`absolute top-3 z-20 flex size-6 cursor-pointer items-center justify-center rounded-full border border-line bg-white text-base leading-none text-ink-soft shadow-[0_1px_3px_rgba(0,0,0,0.12)] transition-colors duration-150 hover:bg-[#edebe5] ${
        isCollapsed ? '-right-8' : 'right-2'
      }`}
      aria-label={isCollapsed ? 'Open sidebar' : 'Close sidebar'}
      aria-expanded={!isCollapsed}
      onClick={() => {
        toggleCollapse();
        persist();
      }}
    >
      {isCollapsed ? '»' : '«'}
    </button>
  );
}
