// src/lib/flow/nodes/entity/FieldsPanel.svelte
<script lang="ts">
    import { onMount } from 'svelte';
    import type { NodePanelProps } from '../types';
    import {
        ENTITY_FIELD_TYPES,
        FIELD_KEY_INFO,
        FIELD_KEY_ORDER,
        resolveFieldKey,
        type EntityData,
        type EntityField,
        type FieldKey
    } from './types';

    let { node, onDataChange }: NodePanelProps = $props();

    // Pull typed fields + the conceptual/physical toggle out of the generic
    // node.data bag. The cast is local so the rest of StylePanel stays
    // shape-agnostic.
    const entity = $derived((node.data ?? {}) as unknown as EntityData);
    const fields = $derived((entity.fields ?? []) as EntityField[]);
    const showDataTypes = $derived(entity.showDataTypes ?? false);

    // Only one dropdown (of either kind) can be open at a time; tracked by
    // index. The two never coexist on the same field — opening one closes
    // the other.
    let openKeyIndex: number | null = $state(null);
    let openTypeIndex: number | null = $state(null);
    let rootEl: HTMLDivElement | undefined = $state();

    onMount(() => {
        const onPointer = (event: PointerEvent) => {
            const target = event.target as Node | null;
            if (rootEl && target && !rootEl.contains(target)) {
                openKeyIndex = null;
                openTypeIndex = null;
            }
        };
        const onKey = (event: KeyboardEvent) => {
            if (event.key === 'Escape') {
                openKeyIndex = null;
                openTypeIndex = null;
            }
        };
        window.addEventListener('pointerdown', onPointer);
        window.addEventListener('keydown', onKey);
        return () => {
            window.removeEventListener('pointerdown', onPointer);
            window.removeEventListener('keydown', onKey);
        };
    });

    function commitFields(next: EntityField[]) {
        onDataChange({ fields: next });
    }

    function patchField(index: number, patch: Partial<EntityField>) {
        commitFields(fields.map((f, i) => (i === index ? { ...f, ...patch } : f)));
    }

    /**
     * Sets a field's key. Also strips the legacy isPK / isFK booleans from
     * the persisted shape so old data doesn't outlive the single-select
     * model on the next save.
     */
    function setFieldKey(index: number, key: FieldKey | undefined) {
        commitFields(
            fields.map((f, i) => {
                if (i !== index) return f;
                const next = { ...f } as EntityField & { isPK?: boolean; isFK?: boolean };
                if (key) next.key = key;
                else delete next.key;
                delete next.isPK;
                delete next.isFK;
                return next;
            })
        );
        openKeyIndex = null;
    }

    function removeField(index: number) {
        commitFields(fields.filter((_, i) => i !== index));
        if (openKeyIndex === index) openKeyIndex = null;
        if (openTypeIndex === index) openTypeIndex = null;
    }

    function addField() {
        commitFields([...fields, { name: 'field' }]);
    }

    function toggleKey(index: number) {
        openKeyIndex = openKeyIndex === index ? null : index;
        openTypeIndex = null;
    }

    function toggleType(index: number) {
        openTypeIndex = openTypeIndex === index ? null : index;
        openKeyIndex = null;
    }

    function selectType(index: number, value: string) {
        patchField(index, { type: value });
        openTypeIndex = null;
    }

    function setShowDataTypes(value: boolean) {
        onDataChange({ showDataTypes: value });
        // If the user just turned types off, close any open type dropdowns
        // so the panel doesn't have an orphan popup hanging around.
        if (!value) openTypeIndex = null;
    }
</script>

{#snippet keyBadge(key: FieldKey | undefined)}
    {#if key}
        <span class="key-badge" data-key={key}>{FIELD_KEY_INFO[key].short}</span>
    {:else}
        <!-- "None" state in the dropdown row uses an em-dash placeholder. -->
        <span class="key-badge key-badge-none">—</span>
    {/if}
{/snippet}

{#snippet chevron(up: boolean)}
    <svg
        viewBox="0 0 24 24"
        width="14"
        height="14"
        fill="none"
        stroke="currentColor"
        stroke-width="2"
        stroke-linecap="round"
        stroke-linejoin="round"
        class="chevron"
        class:up
    >
        <polyline points="6 9 12 15 18 9" />
    </svg>
{/snippet}

<div class="field-editor" bind:this={rootEl}>
    <div class="editor-header">
        <h3 class="group-label">FIELDS</h3>
        <span class="count">{fields.length}</span>
    </div>

    {#each fields as field, i}
        {@const key = resolveFieldKey(field)}
        {@const keyOpen = openKeyIndex === i}
        {@const typeOpen = openTypeIndex === i}
        <div class="field-card" class:editing={keyOpen || typeOpen}>
            <div class="card-row">
                <!-- Key button: colored badge for set keys, key icon for None. -->
                <div class="key-button-wrap">
                    <button
                        type="button"
                        class="key-button"
                        class:open={keyOpen}
                        data-key={key ?? 'NONE'}
                        aria-haspopup="listbox"
                        aria-expanded={keyOpen}
                        aria-label={key ? FIELD_KEY_INFO[key].long : 'Set key'}
                        onclick={() => toggleKey(i)}
                    >
                        {#if key}
                            <span class="key-button-text">{FIELD_KEY_INFO[key].short}</span>
                        {:else}
                            <svg
                                viewBox="0 0 24 24"
                                width="14"
                                height="14"
                                fill="none"
                                stroke="currentColor"
                                stroke-width="1.7"
                                stroke-linecap="round"
                                stroke-linejoin="round"
                                class="key-icon"
                            >
                                <circle cx="9" cy="14" r="4" />
                                <path d="M12 11l9 -9" />
                                <path d="M18 5l2 2" />
                                <path d="M16 7l2 2" />
                            </svg>
                        {/if}
                        {@render chevron(keyOpen)}
                    </button>

                    {#if keyOpen}
                        <ul class="key-dropdown" role="listbox">
                            {#each FIELD_KEY_ORDER as option (option)}
                                {@const info = FIELD_KEY_INFO[option]}
                                {@const isSelected = key === option}
                                <li>
                                    <button
                                        type="button"
                                        role="option"
                                        aria-selected={isSelected}
                                        class="key-option"
                                        class:selected={isSelected}
                                        data-key={option}
                                        onclick={() => setFieldKey(i, option)}
                                    >
                                        {@render keyBadge(option)}
                                        <span class="key-option-label">{info.long}</span>
                                        {#if isSelected}
                                            <svg
                                                viewBox="0 0 24 24"
                                                width="14"
                                                height="14"
                                                fill="none"
                                                stroke="currentColor"
                                                stroke-width="2.4"
                                                stroke-linecap="round"
                                                stroke-linejoin="round"
                                                class="check"
                                            >
                                                <polyline points="5 12 10 17 19 8" />
                                            </svg>
                                        {/if}
                                    </button>
                                </li>
                            {/each}
                            <li class="dropdown-divider" role="separator"></li>
                            <li>
                                <button
                                    type="button"
                                    role="option"
                                    aria-selected={!key}
                                    class="key-option"
                                    class:selected={!key}
                                    onclick={() => setFieldKey(i, undefined)}
                                >
                                    {@render keyBadge(undefined)}
                                    <span class="key-option-label muted">None</span>
                                </button>
                            </li>
                        </ul>
                    {/if}
                </div>

                <input
                    type="text"
                    class="name-input"
                    value={field.name}
                    placeholder="field"
                    oninput={(e) => patchField(i, { name: e.currentTarget.value })}
                    aria-label="Field name"
                />

                <button
                    type="button"
                    class="delete-btn"
                    aria-label="Remove field"
                    onclick={() => removeField(i)}
                >
                    <svg
                        viewBox="0 0 24 24"
                        width="16"
                        height="16"
                        fill="none"
                        stroke="currentColor"
                        stroke-width="1.8"
                        stroke-linecap="round"
                        stroke-linejoin="round"
                    >
                        <polyline points="3 6 5 6 21 6" />
                        <path d="M19 6l-1 14a2 2 0 0 1-2 2H8a2 2 0 0 1-2-2L5 6" />
                        <path d="M10 11v6" />
                        <path d="M14 11v6" />
                        <path d="M9 6V4a1 1 0 0 1 1-1h4a1 1 0 0 1 1 1v2" />
                    </svg>
                </button>
            </div>

            {#if showDataTypes}
                <div class="type-row">
                    <button
                        type="button"
                        class="type-select"
                        class:open={typeOpen}
                        aria-haspopup="listbox"
                        aria-expanded={typeOpen}
                        onclick={() => toggleType(i)}
                    >
                        <span class="type-value">
                            {field.type ? field.type.toUpperCase() : 'TYPE'}
                        </span>
                        {@render chevron(typeOpen)}
                    </button>

                    {#if typeOpen}
                        <ul class="type-dropdown" role="listbox">
                            {#each ENTITY_FIELD_TYPES as option (option)}
                                {@const isSelected = field.type === option}
                                <li>
                                    <button
                                        type="button"
                                        role="option"
                                        aria-selected={isSelected}
                                        class="type-option"
                                        class:selected={isSelected}
                                        onclick={() => selectType(i, option)}
                                    >
                                        <span>{option.toUpperCase()}</span>
                                        {#if isSelected}
                                            <svg
                                                viewBox="0 0 24 24"
                                                width="14"
                                                height="14"
                                                fill="none"
                                                stroke="currentColor"
                                                stroke-width="2.4"
                                                stroke-linecap="round"
                                                stroke-linejoin="round"
                                            >
                                                <polyline points="5 12 10 17 19 8" />
                                            </svg>
                                        {/if}
                                    </button>
                                </li>
                            {/each}
                        </ul>
                    {/if}
                </div>
            {/if}
        </div>
    {/each}

    <button type="button" class="add-field-btn" onclick={addField}>+ Add field</button>

    <!-- Master toggle: drives the type dropdowns here AND whether the entity
         node on the canvas shows each field's type. -->
    <div class="show-types-row">
        <span class="show-types-label">Show data types</span>
        <label class="toggle">
            <input
                type="checkbox"
                checked={showDataTypes}
                onchange={(e) => setShowDataTypes(e.currentTarget.checked)}
            />
            <span class="toggle-slider"></span>
        </label>
    </div>
</div>

<style>
    .field-editor {
        display: flex;
        flex-direction: column;
        gap: 10px;
    }

    .editor-header {
        display: flex;
        align-items: center;
        justify-content: space-between;
    }

    .group-label {
        font-size: 0.7rem;
        letter-spacing: 0.08em;
        font-weight: 700;
        color: #76232f;
        margin: 0;
    }

    .count {
        font-size: 0.78rem;
        color: #8A8B83;
        font-variant-numeric: tabular-nums;
    }

    .field-card {
        background: #ffffff;
        border: 1px solid #D6D2C4;
        border-radius: 8px;
        padding: 10px;
        display: flex;
        flex-direction: column;
        gap: 8px;
        transition: border-color 0.12s ease, box-shadow 0.12s ease;
    }

    /* Mirror the picture: whichever field has an open dropdown gets a red
       outline so it's obvious which row is being edited. */
    .field-card.editing {
        border-color: #a6192e;
        box-shadow: 0 0 0 1px rgba(166, 25, 46, 0.25);
    }

    .card-row {
        display: flex;
        align-items: center;
        gap: 6px;
    }

    /* ─── Key button + dropdown ──────────────────────────────────────── */

    .key-button-wrap {
        position: relative;
        flex-shrink: 0;
    }

    .key-button {
        height: 30px;
        min-width: 52px;
        padding: 0 8px;
        border: 1px solid #D6D2C4;
        background: #ffffff;
        color: #8A8B83;
        border-radius: 6px;
        font-family: inherit;
        font-size: 0.75rem;
        font-weight: 700;
        cursor: pointer;
        display: inline-flex;
        align-items: center;
        gap: 4px;
        transition: background 0.12s ease, border-color 0.12s ease, color 0.12s ease;
    }

    .key-button:hover {
        border-color: #C4C1B8;
    }

    /* Open state — only the chevron flips; border stays as-is so the
       overall card-border + open state combine cleanly. */
    .key-button.open {
        border-color: #a6192e;
    }

    /* Color the button by its currently selected key. */
    .key-button[data-key='PK'] {
        background: #fae9c8;
        color: #854f0b;
        border-color: #d8a85a;
    }
    .key-button[data-key='FK'] {
        background: #dce9fa;
        color: #1e4380;
        border-color: #7aa6e6;
    }
    .key-button[data-key='PI'] {
        background: #c8eae0;
        color: #0b6354;
        border-color: #5fb59f;
    }
    .key-button[data-key='WPI'] {
        background: #e3d8fa;
        color: #5a3fb0;
        border-color: #a18de0;
    }

    .key-button-text {
        line-height: 1;
    }

    .key-icon {
        opacity: 0.85;
    }

    .chevron {
        flex-shrink: 0;
        opacity: 0.7;
        transition: transform 0.15s ease;
    }

    .chevron.up {
        transform: rotate(180deg);
    }

    .key-dropdown {
        position: absolute;
        top: calc(100% + 4px);
        left: 0;
        list-style: none;
        margin: 0;
        padding: 4px;
        background: #ffffff;
        border: 1px solid #D6D2C4;
        border-radius: 8px;
        box-shadow: 0 12px 24px rgba(0, 0, 0, 0.12);
        z-index: 200;
        min-width: 200px;
    }

    .key-dropdown li {
        list-style: none;
    }

    .key-option {
        width: 100%;
        background: transparent;
        border: none;
        padding: 8px 10px;
        font-family: inherit;
        font-size: 0.82rem;
        color: #373A36;
        text-align: left;
        cursor: pointer;
        border-radius: 4px;
        display: flex;
        align-items: center;
        gap: 10px;
        transition: background 0.1s ease;
    }

    .key-option:hover {
        background: #F5F3EF;
    }

    /* Tint the selected row with the key's own color so the dropdown
       reads like a row of stained pills. */
    .key-option[data-key='PK'].selected {
        background: #fff5e0;
    }
    .key-option[data-key='FK'].selected {
        background: #eaf2fd;
    }
    .key-option[data-key='PI'].selected {
        background: #d9f1e9;
    }
    .key-option[data-key='WPI'].selected {
        background: #ede4fc;
    }

    .key-option-label {
        flex: 1;
        font-weight: 500;
    }

    .key-option-label.muted {
        color: #8A8B83;
        font-weight: 400;
    }

    .check {
        color: #76232f;
        flex-shrink: 0;
    }

    .dropdown-divider {
        height: 1px;
        background: #E8E5DE;
        margin: 4px 4px;
    }

    /* ─── Key badge (used inside dropdown rows) ──────────────────────── */

    .key-badge {
        display: inline-flex;
        align-items: center;
        justify-content: center;
        min-width: 36px;
        padding: 2px 6px;
        border-radius: 4px;
        font-size: 0.72rem;
        font-weight: 700;
        line-height: 1.4;
        flex-shrink: 0;
    }

    .key-badge[data-key='PK'] {
        background: #fae9c8;
        color: #854f0b;
    }
    .key-badge[data-key='FK'] {
        background: #dce9fa;
        color: #1e4380;
    }
    .key-badge[data-key='PI'] {
        background: #c8eae0;
        color: #0b6354;
    }
    .key-badge[data-key='WPI'] {
        background: #e3d8fa;
        color: #5a3fb0;
    }

    .key-badge-none {
        background: transparent;
        color: #b8b8b8;
        font-weight: 400;
    }

    /* ─── Name input + delete ────────────────────────────────────────── */

    .name-input {
        flex: 1;
        min-width: 0;
        border: 1px solid #D6D2C4;
        border-radius: 6px;
        padding: 8px 10px;
        font-family: inherit;
        font-size: 0.9rem;
        outline: none;
        background: #ffffff;
        color: #373A36;
    }

    .name-input:focus {
        border-color: #a6192e;
    }

    .delete-btn {
        width: 32px;
        height: 32px;
        border: none;
        background: transparent;
        color: #8A8B83;
        cursor: pointer;
        border-radius: 6px;
        display: flex;
        align-items: center;
        justify-content: center;
        flex-shrink: 0;
        transition: background 0.12s ease, color 0.12s ease;
    }

    .delete-btn:hover {
        background: #fdf2f1;
        color: #b42318;
    }

    /* ─── Type row (only when showDataTypes is on) ───────────────────── */

    .type-row {
        position: relative;
    }

    .type-select {
        width: 100%;
        height: 32px;
        padding: 0 10px;
        border: 1px solid #D6D2C4;
        background: #ffffff;
        color: #373A36;
        border-radius: 6px;
        font-family: inherit;
        font-size: 0.78rem;
        font-weight: 600;
        cursor: pointer;
        display: flex;
        align-items: center;
        justify-content: space-between;
        gap: 6px;
        transition: border-color 0.12s ease;
    }

    .type-select.open {
        border-color: #a6192e;
        color: #76232f;
    }

    .type-value {
        overflow: hidden;
        text-overflow: ellipsis;
        white-space: nowrap;
    }

    .type-dropdown {
        position: absolute;
        top: calc(100% + 4px);
        left: 0;
        right: 0;
        list-style: none;
        margin: 0;
        padding: 4px;
        background: #ffffff;
        border: 1px solid #D6D2C4;
        border-radius: 8px;
        box-shadow: 0 12px 24px rgba(0, 0, 0, 0.12);
        z-index: 200;
        max-height: 220px;
        overflow-y: auto;
    }

    .type-dropdown li {
        list-style: none;
    }

    .type-option {
        width: 100%;
        background: transparent;
        border: none;
        padding: 8px 10px;
        font-family: inherit;
        font-size: 0.78rem;
        font-weight: 600;
        color: #373A36;
        text-align: left;
        cursor: pointer;
        border-radius: 4px;
        display: flex;
        align-items: center;
        justify-content: space-between;
        gap: 6px;
        transition: background 0.1s ease, color 0.1s ease;
    }

    .type-option:hover {
        background: #fbeef0;
        color: #76232f;
    }

    .type-option.selected {
        color: #76232f;
    }

    /* ─── Add-field button + show-types toggle ───────────────────────── */

    .add-field-btn {
        width: 100%;
        padding: 10px;
        border: 1px dashed #C4C1B8;
        background: transparent;
        color: #8A8B83;
        border-radius: 8px;
        font-family: inherit;
        font-size: 0.85rem;
        cursor: pointer;
        transition: border-color 0.12s ease, color 0.12s ease, background 0.12s ease;
    }

    .add-field-btn:hover {
        border-color: #76232f;
        color: #76232f;
        background: #fbeef0;
    }

    .show-types-row {
        display: flex;
        align-items: center;
        justify-content: space-between;
        padding-top: 4px;
    }

    .show-types-label {
        font-size: 0.85rem;
        color: #373A36;
    }

    .toggle {
        position: relative;
        width: 36px;
        height: 20px;
        display: inline-block;
        flex-shrink: 0;
    }

    .toggle input {
        opacity: 0;
        width: 0;
        height: 0;
    }

    .toggle-slider {
        position: absolute;
        inset: 0;
        background: #d0cabd;
        border-radius: 999px;
        cursor: pointer;
        transition: background 0.15s ease;
    }

    .toggle-slider::before {
        content: '';
        position: absolute;
        top: 2px;
        left: 2px;
        width: 16px;
        height: 16px;
        background: #ffffff;
        border-radius: 50%;
        transition: transform 0.15s ease;
        box-shadow: 0 1px 2px rgba(0, 0, 0, 0.15);
    }

    .toggle input:checked + .toggle-slider {
        background: #a6192e;
    }

    .toggle input:checked + .toggle-slider::before {
        transform: translateX(16px);
    }
</style>

// client/src/lib/flow/nodes/entity-relation/entity/FieldsPanel.tsx
'use client';

import { useEffect, useRef, useState } from 'react';
import type { NodePanelProps } from '@/lib/flow/nodes/types';
import {
  ENTITY_FIELD_TYPES,
  FIELD_KEY_INFO,
  FIELD_KEY_ORDER,
  resolveFieldKey,
  type EntityData,
  type EntityField,
  type FieldKey,
} from './types';

// Per-key palettes (button = filled pill; badge = same minus border;
// option-selected = a faint tint of the same hue).
const KEY_BUTTON_CLASS: Record<FieldKey, string> = {
  PK: 'bg-[#fae9c8] text-[#854f0b] border-[#d8a85a]',
  FK: 'bg-[#dce9fa] text-[#1e4380] border-[#7aa6e6]',
  PI: 'bg-[#c8eae0] text-[#0b6354] border-[#5fb59f]',
  WPI: 'bg-[#e3d8fa] text-[#5a3fb0] border-[#a18de0]',
};
const KEY_BADGE_CLASS: Record<FieldKey, string> = {
  PK: 'bg-[#fae9c8] text-[#854f0b]',
  FK: 'bg-[#dce9fa] text-[#1e4380]',
  PI: 'bg-[#c8eae0] text-[#0b6354]',
  WPI: 'bg-[#e3d8fa] text-[#5a3fb0]',
};
const KEY_OPTION_SELECTED_BG: Record<FieldKey, string> = {
  PK: 'bg-[#fff5e0]',
  FK: 'bg-[#eaf2fd]',
  PI: 'bg-[#d9f1e9]',
  WPI: 'bg-[#ede4fc]',
};

function KeyBadge({ fieldKey }: { fieldKey?: FieldKey }) {
  if (fieldKey) {
    return (
      <span
        className={`${KEY_BADGE_CLASS[fieldKey]} inline-flex min-w-[36px] flex-shrink-0 items-center justify-center rounded px-1.5 py-0.5 text-[0.72rem] leading-[1.4] font-bold`}
      >
        {FIELD_KEY_INFO[fieldKey].short}
      </span>
    );
  }
  // "None" state uses an em-dash placeholder.
  return (
    <span className="inline-flex min-w-[36px] flex-shrink-0 items-center justify-center rounded bg-transparent px-1.5 py-0.5 text-[0.72rem] leading-[1.4] font-normal text-[#b8b8b8]">
      —
    </span>
  );
}

function Chevron({ up }: { up: boolean }) {
  return (
    <svg
      viewBox="0 0 24 24"
      width="14"
      height="14"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      className={`flex-shrink-0 opacity-70 transition-transform duration-150 ${up ? 'rotate-180' : ''}`}
    >
      <polyline points="6 9 12 15 18 9" />
    </svg>
  );
}

export default function FieldsPanel({ node, onDataChange }: NodePanelProps) {
  const entity = (node.data ?? {}) as unknown as EntityData;
  const fields = (entity.fields ?? []) as EntityField[];
  const showDataTypes = entity.showDataTypes ?? false;

  // A dropdown is identified by field index AND which selector (main/optional).
  // Only one (of either kind) is open at a time.
  const [openKey, setOpenKey] = useState<{ index: number; which: 'main' | 'optional' } | null>(null);
  const [openTypeIndex, setOpenTypeIndex] = useState<number | null>(null);
  const rootRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const onPointer = (event: PointerEvent) => {
      const target = event.target as Node | null;
      if (rootRef.current && target && !rootRef.current.contains(target)) {
        setOpenKey(null);
        setOpenTypeIndex(null);
      }
    };
    const onKey = (event: KeyboardEvent) => {
      if (event.key === 'Escape') {
        setOpenKey(null);
        setOpenTypeIndex(null);
      }
    };
    window.addEventListener('pointerdown', onPointer);
    window.addEventListener('keydown', onKey);
    return () => {
      window.removeEventListener('pointerdown', onPointer);
      window.removeEventListener('keydown', onKey);
    };
  }, []);

  function commitFields(next: EntityField[]) {
    onDataChange({ fields: next }, { resetHeight: true });
  }

  function patchField(index: number, patch: Partial<EntityField>) {
    commitFields(fields.map((f, i) => (i === index ? { ...f, ...patch } : f)));
  }

  // Sets a field's main OR optional key. The main key also strips legacy
  // isPK/isFK booleans so old data doesn't outlive the single-select model.
  function setFieldKey(index: number, which: 'main' | 'optional', key: FieldKey | undefined) {
    commitFields(
      fields.map((f, i) => {
        if (i !== index) return f;
        const next = { ...f } as EntityField & { isPK?: boolean; isFK?: boolean };
        if (which === 'main') {
          if (key) next.key = key;
          else delete next.key;
          delete next.isPK;
          delete next.isFK;
        } else {
          if (key) next.optionalKey = key;
          else delete next.optionalKey;
        }
        return next;
      }),
    );
    setOpenKey(null);
  }

  function removeField(index: number) {
    commitFields(fields.filter((_, i) => i !== index));
    if (openKey?.index === index) setOpenKey(null);
    if (openTypeIndex === index) setOpenTypeIndex(null);
  }

  function addField() {
    commitFields([...fields, { name: 'field' }]);
  }

  function toggleKey(index: number, which: 'main' | 'optional') {
    setOpenKey((prev) => (prev && prev.index === index && prev.which === which ? null : { index, which }));
    setOpenTypeIndex(null);
  }

  function toggleType(index: number) {
    setOpenTypeIndex((prev) => (prev === index ? null : index));
    setOpenKey(null);
  }

  function selectType(index: number, value: string) {
    patchField(index, { type: value });
    setOpenTypeIndex(null);
  }

  function setShowDataTypes(value: boolean) {
    onDataChange({ showDataTypes: value }, { resetHeight: true });
    if (!value) setOpenTypeIndex(null);
  }

  // One key selector (button + dropdown). Used twice per field.
  const renderKeySelector = (
    index: number,
    which: 'main' | 'optional',
    currentKey: FieldKey | undefined,
    isOpen: boolean,
  ) => (
    <div className="relative flex-shrink-0">
      <button
        type="button"
        className={`inline-flex h-[30px] cursor-pointer items-center gap-1 rounded-md border px-2 text-[0.75rem] font-bold transition-colors duration-[120ms] ${
          which === 'main' ? 'min-w-[52px]' : 'min-w-[46px]'
        } ${
          currentKey
            ? KEY_BUTTON_CLASS[currentKey]
            : isOpen
              ? 'border-mq-red bg-white text-ink-muted'
              : which === 'optional'
                ? 'border-dashed border-[#c4c1b8] bg-white text-ink-muted hover:border-mq-red'
                : 'border-line bg-white text-ink-muted hover:border-[#c4c1b8]'
        }`}
        aria-haspopup="listbox"
        aria-expanded={isOpen}
        aria-label={
          currentKey
            ? FIELD_KEY_INFO[currentKey].long
            : which === 'optional'
              ? 'Set optional key'
              : 'Set key'
        }
        onClick={() => toggleKey(index, which)}
      >
        {currentKey ? (
          <span className="leading-none">{FIELD_KEY_INFO[currentKey].short}</span>
        ) : (
          <svg
            viewBox="0 0 24 24"
            width="14"
            height="14"
            fill="none"
            stroke="currentColor"
            strokeWidth="1.7"
            strokeLinecap="round"
            strokeLinejoin="round"
            className="opacity-[0.85]"
          >
            <circle cx="9" cy="14" r="4" />
            <path d="M12 11l9 -9" />
            <path d="M18 5l2 2" />
            <path d="M16 7l2 2" />
          </svg>
        )}
        <Chevron up={isOpen} />
      </button>

      {isOpen && (
        <ul
          className="absolute top-[calc(100%+4px)] left-0 z-[200] m-0 min-w-[200px] list-none rounded-lg border border-line bg-white p-1 shadow-[0_12px_24px_rgba(0,0,0,0.12)]"
          role="listbox"
        >
          {FIELD_KEY_ORDER.map((option) => {
            const info = FIELD_KEY_INFO[option];
            const isSelected = currentKey === option;
            return (
              <li key={option}>
                <button
                  type="button"
                  role="option"
                  aria-selected={isSelected}
                  className={`flex w-full cursor-pointer items-center gap-2.5 rounded border-none bg-transparent px-2.5 py-2 text-left text-[0.82rem] text-ink-soft transition-colors duration-100 ${
                    isSelected ? KEY_OPTION_SELECTED_BG[option] : 'hover:bg-panel'
                  }`}
                  onClick={() => setFieldKey(index, which, option)}
                >
                  <KeyBadge fieldKey={option} />
                  <span className="flex-1 font-medium">{info.long}</span>
                  {isSelected && (
                    <svg
                      viewBox="0 0 24 24"
                      width="14"
                      height="14"
                      fill="none"
                      stroke="currentColor"
                      strokeWidth="2.4"
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      className="flex-shrink-0 text-mq-maroon"
                    >
                      <polyline points="5 12 10 17 19 8" />
                    </svg>
                  )}
                </button>
              </li>
            );
          })}
          <li className="mx-1 my-1 h-px list-none bg-[#e8e5de]" role="separator" />
          <li>
            <button
              type="button"
              role="option"
              aria-selected={!currentKey}
              className="flex w-full cursor-pointer items-center gap-2.5 rounded border-none bg-transparent px-2.5 py-2 text-left text-[0.82rem] text-ink-soft transition-colors duration-100 hover:bg-panel"
              onClick={() => setFieldKey(index, which, undefined)}
            >
              <KeyBadge />
              <span className="flex-1 font-normal text-ink-muted">None</span>
            </button>
          </li>
        </ul>
      )}
    </div>
  );

  return (
    <div className="flex flex-col gap-2.5" ref={rootRef}>
      <div className="flex items-center justify-between">
        <h3 className="m-0 text-[0.7rem] font-bold tracking-[0.08em] text-mq-maroon">FIELDS</h3>
        <span className="text-[0.78rem] tabular-nums text-ink-muted">{fields.length}</span>
      </div>

      {fields.map((field, i) => {
        const key = resolveFieldKey(field);
        const keyOpen = openKey?.index === i;
        const typeOpen = openTypeIndex === i;
        return (
          <div
            key={i}
            className={`flex flex-col gap-2 rounded-lg border bg-white p-2.5 transition-[border-color,box-shadow] duration-[120ms] ${
              keyOpen || typeOpen
                ? 'border-mq-red shadow-[0_0_0_1px_rgba(166,25,46,0.25)]'
                : 'border-line'
            }`}
          >
            <div className="flex items-center gap-1.5">
              {renderKeySelector(i, 'main', key, keyOpen && openKey?.which === 'main')}
              {renderKeySelector(i, 'optional', field.optionalKey, keyOpen && openKey?.which === 'optional')}

              <input
                type="text"
                className="min-w-0 flex-1 rounded-md border border-line bg-white px-2.5 py-2 text-[0.9rem] text-ink-soft outline-none focus:border-mq-red"
                value={field.name}
                placeholder="field"
                onInput={(e) => patchField(i, { name: e.currentTarget.value })}
                aria-label="Field name"
              />

              <button
                type="button"
                className="flex h-8 w-8 flex-shrink-0 cursor-pointer items-center justify-center rounded-md border-none bg-transparent text-ink-muted transition-colors duration-[120ms] hover:bg-[#fdf2f1] hover:text-[#b42318]"
                aria-label="Remove field"
                onClick={() => removeField(i)}
              >
                <svg
                  viewBox="0 0 24 24"
                  width="16"
                  height="16"
                  fill="none"
                  stroke="currentColor"
                  strokeWidth="1.8"
                  strokeLinecap="round"
                  strokeLinejoin="round"
                >
                  <polyline points="3 6 5 6 21 6" />
                  <path d="M19 6l-1 14a2 2 0 0 1-2 2H8a2 2 0 0 1-2-2L5 6" />
                  <path d="M10 11v6" />
                  <path d="M14 11v6" />
                  <path d="M9 6V4a1 1 0 0 1 1-1h4a1 1 0 0 1 1 1v2" />
                </svg>
              </button>
            </div>

            {showDataTypes && (
              <div className="relative">
                <button
                  type="button"
                  className={`flex h-8 w-full cursor-pointer items-center justify-between gap-1.5 rounded-md border bg-white px-2.5 text-[0.78rem] font-semibold transition-colors duration-[120ms] ${
                    typeOpen ? 'border-mq-red text-mq-maroon' : 'border-line text-ink-soft'
                  }`}
                  aria-haspopup="listbox"
                  aria-expanded={typeOpen}
                  onClick={() => toggleType(i)}
                >
                  <span className="overflow-hidden text-ellipsis whitespace-nowrap">
                    {field.type ? field.type.toUpperCase() : 'TYPE'}
                  </span>
                  <Chevron up={typeOpen} />
                </button>

                {typeOpen && (
                  <ul
                    className="absolute top-[calc(100%+4px)] right-0 left-0 z-[200] m-0 max-h-[220px] list-none overflow-y-auto rounded-lg border border-line bg-white p-1 shadow-[0_12px_24px_rgba(0,0,0,0.12)]"
                    role="listbox"
                  >
                    {ENTITY_FIELD_TYPES.map((option) => {
                      const isSelected = field.type === option;
                      return (
                        <li key={option}>
                          <button
                            type="button"
                            role="option"
                            aria-selected={isSelected}
                            className={`flex w-full cursor-pointer items-center justify-between gap-1.5 rounded border-none bg-transparent px-2.5 py-2 text-left text-[0.78rem] font-semibold transition-colors duration-100 hover:bg-mq-pink hover:text-mq-maroon ${
                              isSelected ? 'text-mq-maroon' : 'text-ink-soft'
                            }`}
                            onClick={() => selectType(i, option)}
                          >
                            <span>{option.toUpperCase()}</span>
                            {isSelected && (
                              <svg
                                viewBox="0 0 24 24"
                                width="14"
                                height="14"
                                fill="none"
                                stroke="currentColor"
                                strokeWidth="2.4"
                                strokeLinecap="round"
                                strokeLinejoin="round"
                              >
                                <polyline points="5 12 10 17 19 8" />
                              </svg>
                            )}
                          </button>
                        </li>
                      );
                    })}
                  </ul>
                )}
              </div>
            )}
          </div>
        );
      })}

      <button
        type="button"
        className="w-full cursor-pointer rounded-lg border border-dashed border-[#c4c1b8] bg-transparent p-2.5 text-[0.85rem] text-ink-muted transition-colors duration-[120ms] hover:border-mq-maroon hover:bg-mq-pink hover:text-mq-maroon"
        onClick={addField}
      >
        + Add field
      </button>

      {/* Master toggle: drives the type dropdowns here AND whether the entity
          node shows each field's type. */}
      <div className="flex items-center justify-between pt-1">
        <span className="text-[0.85rem] text-ink-soft">Show data types</span>
        <label className="relative inline-block h-5 w-9 flex-shrink-0">
          <input
            className="peer h-0 w-0 opacity-0"
            type="checkbox"
            checked={showDataTypes}
            onChange={(e) => setShowDataTypes(e.currentTarget.checked)}
          />
          <span className="absolute inset-0 cursor-pointer rounded-full bg-[#d0cabd] transition-colors duration-150 before:absolute before:top-0.5 before:left-0.5 before:h-4 before:w-4 before:rounded-full before:bg-white before:shadow-[0_1px_2px_rgba(0,0,0,0.15)] before:transition-transform before:duration-150 before:content-[''] peer-checked:bg-mq-red peer-checked:before:translate-x-4" />
        </label>
      </div>
    </div>
  );
}
