// client/src/lib/components/toolbar/ToolBar.svelte
<script lang="ts">
	import { getContext, onMount } from 'svelte';
	import { FolderOpen, Save } from '@lucide/svelte';
	import { FONT_FAMILIES } from '$lib/fonts';
	import type { NodeStyleData } from '$lib/components/StylePanel.svelte';

	interface NodeTextStyle {
		fontFamily: string;
		fontSize: number;
		bold: boolean;
		italic: boolean;
		underline: boolean;
		textColor: string;
	}

	interface EditorContext {
		state: { zoomPercent: number; locked: boolean };
		history: { canUndo: boolean; canRedo: boolean };
		save: () => void;
		open: () => void;
		newFile: () => void;
		undo: () => void;
		redo: () => void;
		zoomIn: () => void;
		zoomOut: () => void;
		fitView: () => void;
		fitSelection: () => void;
		setZoom: (percent: number) => void;
		toggleLock: () => void;
		copy: () => void;
		duplicate: () => void;
		deleteSelected: () => void;
		// Text formatting of the selected node (null when nothing is selected).
		nodeStyle: NodeTextStyle | null;
		applyStyle: (patch: NodeStyleData) => void;
	}

	const editor = getContext<EditorContext>('editor');

	const ZOOM_PRESETS = [25, 50, 75, 100, 125, 150, 200];
	const FONT_SIZES = [8, 9, 10, 11, 12, 14, 16, 18, 24, 36, 48, 64];

	// Single open-dropdown tracker for the three menus (zoom / font / size).
	let openDropdown = $state<'zoom' | 'font' | 'size' | null>(null);
	const toggle = (name: 'zoom' | 'font' | 'size') =>
		(openDropdown = openDropdown === name ? null : name);
	const closeDropdowns = () => (openDropdown = null);

	// Current text style (falls back to sensible defaults when no selection so
	// the controls still read cleanly).
	const style = $derived(
		editor.nodeStyle ?? {
			fontFamily: 'Inter',
			fontSize: 14,
			bold: false,
			italic: false,
			underline: false,
			textColor: '#2c2c2a'
		}
	);

	function pickZoom(percent: number) {
		editor.setZoom(percent);
		closeDropdowns();
	}
	function pickFitView() {
		editor.fitView();
		closeDropdowns();
	}
	function pickFitSelection() {
		editor.fitSelection();
		closeDropdowns();
	}
	function pickFont(family: string) {
		editor.applyStyle({ fontFamily: family });
		closeDropdowns();
	}
	function pickSize(size: number) {
		editor.applyStyle({ fontSize: size });
		closeDropdowns();
	}

	// ─── Text colour ────────────────────────────────────────────────────
	// Live mirror of the colour picker so the swatch (the line under "A")
	// reflects the chosen colour the instant it changes — even mid-drag and
	// even with nothing selected. Falls back to the selected element's colour
	// when not actively picking; reset on `change` so it follows selection again.
	let liveTextColor = $state<string | null>(null);
	const swatchColor = $derived(liveTextColor ?? style.textColor);

	function onTextColorInput(event: Event) {
		const value = (event.currentTarget as HTMLInputElement).value;
		liveTextColor = value;
		editor.applyStyle({ textColor: value });
	}

	// ─── Editable zoom % / font size ────────────────────────────────────
	// Each field shows the live value until the user focuses it; from then on
	// it shows a local draft string so typing isn't clobbered by reactive
	// updates. Enter / blur commits (clamped); Escape cancels. `null` draft =
	// not editing → display the live value.
	let zoomDraft = $state<string | null>(null);
	let sizeDraft = $state<string | null>(null);

	const ZOOM_MIN = 10;
	const ZOOM_MAX = 400;
	const SIZE_MIN = 1;
	const SIZE_MAX = 96;

	const clamp = (n: number, min: number, max: number) => Math.min(max, Math.max(min, n));

	function commitZoom() {
		if (zoomDraft !== null) {
			const n = parseInt(zoomDraft, 10);
			if (!Number.isNaN(n)) editor.setZoom(clamp(n, ZOOM_MIN, ZOOM_MAX));
		}
		zoomDraft = null;
	}

	function commitSize() {
		if (sizeDraft !== null) {
			const n = parseInt(sizeDraft, 10);
			if (!Number.isNaN(n)) editor.applyStyle({ fontSize: clamp(n, SIZE_MIN, SIZE_MAX) });
		}
		sizeDraft = null;
	}

	// Enter commits + blurs; Escape discards the draft. stopPropagation keeps the
	// keystrokes out of the editor's global shortcut handler while typing.
	function onNumberKeydown(event: KeyboardEvent, commit: () => void, cancel: () => void) {
		event.stopPropagation();
		const input = event.currentTarget as HTMLInputElement;
		if (event.key === 'Enter') {
			event.preventDefault();
			commit();
			input.blur();
		} else if (event.key === 'Escape') {
			event.preventDefault();
			cancel();
			input.blur();
		}
	}

	// Focusing a field starts editing from the current value and selects it, so
	// the user can just type the new number. Any open preset menu is closed.
	function focusNumber(event: FocusEvent, set: (v: string) => void, current: number) {
		closeDropdowns();
		set(`${current}`);
		(event.currentTarget as HTMLInputElement).select();
	}

	// Icon buttons: the `tb-tip` marker drives the hover tooltip (see the small
	// scoped block below — a pseudo-element with `content: attr(aria-label)` is
	// the one thing Tailwind can't express: its `--tw-content` var overrides the
	// arbitrary `attr()` and the tooltip renders empty). `toggled` is applied via
	// class:toggled where needed; the [&.toggled] rules only bite when present.
	const ICON_BTN = [
		'tb-tip relative inline-flex h-8 w-8 cursor-pointer items-center justify-center rounded-md border',
		'border-transparent bg-transparent p-0 text-toolbar-text transition-colors duration-[120ms]',
		'[&_svg]:size-[18px] enabled:hover:bg-surface-hover enabled:hover:text-[#1f201d]',
		'disabled:cursor-not-allowed disabled:opacity-[0.32] [&.toggled]:bg-mq-pink [&.toggled]:text-mq-red'
	].join(' ');
	// Bold / Italic / Underline / Color buttons: `tb-tip-data` tooltip = data-tip.
	const FMT_BTN = [
		'tb-tip-data relative inline-flex h-8 w-8 cursor-pointer items-center justify-center rounded-md border',
		'border-transparent bg-transparent p-0 text-toolbar-text transition-colors duration-[120ms]',
		'hover:bg-surface-hover hover:text-[#1f201d] [&.toggled]:bg-mq-pink [&.toggled]:text-mq-red'
	].join(' ');

	onMount(() => {
		const onPointer = (event: PointerEvent) => {
			const target = event.target as HTMLElement | null;
			if (target?.closest('.tb-menu')) return;
			closeDropdowns();
		};
		const onKey = (event: KeyboardEvent) => {
			if (event.key === 'Escape') closeDropdowns();
		};
		window.addEventListener('pointerdown', onPointer);
		window.addEventListener('keydown', onKey);
		return () => {
			window.removeEventListener('pointerdown', onPointer);
			window.removeEventListener('keydown', onKey);
		};
	});
</script>

{#snippet icon(name: string)}
	<svg
		viewBox="0 0 24 24"
		fill="none"
		stroke="currentColor"
		stroke-width="1.8"
		stroke-linecap="round"
		stroke-linejoin="round"
	>
		{#if name === 'undo'}
			<polyline points="9 14 4 9 9 4" />
			<path d="M4 9h11a5 5 0 0 1 5 5v0a5 5 0 0 1-5 5h-4" />
		{:else if name === 'redo'}
			<polyline points="15 14 20 9 15 4" />
			<path d="M20 9H9a5 5 0 0 0-5 5v0a5 5 0 0 0 5 5h4" />
		{:else if name === 'zoom-in'}
			<circle cx="11" cy="11" r="7" />
			<line x1="20" y1="20" x2="16" y2="16" />
			<line x1="11" y1="8" x2="11" y2="14" />
			<line x1="8" y1="11" x2="14" y2="11" />
		{:else if name === 'zoom-out'}
			<circle cx="11" cy="11" r="7" />
			<line x1="20" y1="20" x2="16" y2="16" />
			<line x1="8" y1="11" x2="14" y2="11" />
		{:else if name === 'fullscreen'}
			<polyline points="9 4 4 4 4 9" />
			<polyline points="15 4 20 4 20 9" />
			<polyline points="9 20 4 20 4 15" />
			<polyline points="15 20 20 20 20 15" />
		{:else if name === 'lock-closed'}
			<rect x="5" y="11" width="14" height="10" rx="2" />
			<path d="M8 11V7a4 4 0 0 1 8 0v4" />
		{:else if name === 'lock-open'}
			<rect x="5" y="11" width="14" height="10" rx="2" />
			<path d="M8 11V7a4 4 0 0 1 7.5 -2" />
		{:else if name === 'copy'}
			<rect x="9" y="9" width="11" height="11" rx="2" />
			<path d="M5 15H4a1 1 0 0 1-1-1V4a1 1 0 0 1 1-1h10a1 1 0 0 1 1 1v1" />
		{:else if name === 'delete'}
			<polyline points="3 6 5 6 21 6" />
			<path d="M19 6l-1 14a2 2 0 0 1-2 2H8a2 2 0 0 1-2-2L5 6" />
			<path d="M10 11v6" />
			<path d="M14 11v6" />
			<path d="M9 6V4a1 1 0 0 1 1-1h4a1 1 0 0 1 1 1v2" />
		{:else if name === 'chevron'}
			<polyline points="6 9 12 15 18 9" />
		{:else if name === 'check'}
			<polyline points="5 12 10 17 19 8" />
		{:else if name === 'fit'}
			<polyline points="4 9 4 4 9 4" />
			<polyline points="20 9 20 4 15 4" />
			<polyline points="4 15 4 20 9 20" />
			<polyline points="20 15 20 20 15 20" />
		{/if}
	</svg>
{/snippet}

<div
	class="flex w-full flex-[0_0_46px] items-center gap-1 border-b border-line-soft bg-white px-3
		[font-family:system-ui,-apple-system,sans-serif]"
>
	<!-- File -->
	<div class="flex items-center gap-0.5">
		<button type="button" class={ICON_BTN} aria-label="Open file" onclick={editor.open}>
			<FolderOpen size={18} />
		</button>
		<button type="button" class={ICON_BTN} aria-label="Save" onclick={editor.save}>
			<Save size={18} />
		</button>
	</div>

	<div class="mx-1.5 h-[22px] w-px bg-line-soft"></div>

	<!-- History -->
	<div class="flex items-center gap-0.5">
		<button
			type="button"
			class={ICON_BTN}
			aria-label="Undo"
			onclick={editor.undo}
			disabled={!editor.history.canUndo}
		>
			{@render icon('undo')}
		</button>
		<button
			type="button"
			class={ICON_BTN}
			aria-label="Redo"
			onclick={editor.redo}
			disabled={!editor.history.canRedo}
		>
			{@render icon('redo')}
		</button>
	</div>

	<div class="mx-1.5 h-[22px] w-px bg-line-soft"></div>

	<!-- Zoom -->
	<div class="flex items-center gap-0.5">
		<button type="button" class={ICON_BTN} aria-label="Zoom out" onclick={editor.zoomOut}>
			{@render icon('zoom-out')}
		</button>

		<div class="tb-menu relative">
			<div
				class="group inline-flex h-[30px] min-w-[64px] items-center rounded-md border border-line-soft
					bg-transparent pr-0.5 pl-2 transition-colors duration-[120ms] hover:bg-surface-hover
					focus-within:border-mq-red focus-within:bg-white [&.active]:border-mq-red [&.active]:bg-white"
				class:active={openDropdown === 'zoom'}
			>
				<input
					class="w-0 min-w-[26px] flex-1 border-none bg-transparent p-0 text-right text-[0.82rem]
						tabular-nums text-toolbar-text outline-none [appearance:textfield]
						group-focus-within:text-[#1f201d]
						[&::-webkit-inner-spin-button]:appearance-none [&::-webkit-outer-spin-button]:appearance-none"
					type="text"
					inputmode="numeric"
					aria-label="Zoom level"
					value={zoomDraft ?? `${editor.state.zoomPercent}`}
					oninput={(e) => (zoomDraft = e.currentTarget.value)}
					onfocus={(e) =>
						focusNumber(e, (v) => (zoomDraft = v), editor.state.zoomPercent)}
					onblur={commitZoom}
					onkeydown={(e) => onNumberKeydown(e, commitZoom, () => (zoomDraft = null))}
				/>
				<span class="pointer-events-none mr-px ml-0.5 text-[0.82rem] text-ink-muted">%</span>
				<button
					type="button"
					class="inline-flex h-full w-4 cursor-pointer items-center justify-center border-none
						bg-transparent p-0 text-ink-muted hover:text-toolbar-text [&_svg]:size-3"
					aria-label="Zoom presets"
					aria-haspopup="menu"
					aria-expanded={openDropdown === 'zoom'}
					onclick={() => toggle('zoom')}
				>
					{@render icon('chevron')}
				</button>
			</div>

			{#if openDropdown === 'zoom'}
				<div
					class="absolute top-[calc(100%+6px)] left-0 z-[100] flex max-h-[320px] min-w-[180px]
						flex-col gap-px overflow-y-auto rounded-[10px] border border-line-dropdown bg-white p-1.5
						shadow-[0_12px_28px_rgba(0,0,0,0.14)]"
					role="menu"
				>
					<div class="px-3 pt-1.5 pb-1 text-[0.66rem] font-bold tracking-[0.08em] text-ink-muted">
						ZOOM LEVEL
					</div>
					{#each ZOOM_PRESETS as preset}
						<button
							type="button"
							role="menuitem"
							class="flex w-full cursor-pointer items-center gap-1.5 rounded-md border-none
								bg-transparent px-3 py-[7px] text-left text-[0.86rem] text-ink-soft transition-colors
								duration-100 hover:bg-mq-pink hover:text-mq-maroon [&.checked]:bg-mq-pink
								[&.checked]:text-mq-maroon"
							class:checked={preset === editor.state.zoomPercent}
							onclick={() => pickZoom(preset)}
						>
							<span
								class="inline-flex h-4 w-4 flex-shrink-0 items-center justify-center text-mq-maroon
									[&_svg]:size-3.5"
							>
								{#if preset === editor.state.zoomPercent}{@render icon('check')}{/if}
							</span>
							<span class="flex-1 text-left tabular-nums">{preset}%</span>
						</button>
					{/each}
					<div class="mx-1 my-1 h-px bg-[#e8e5de]"></div>
					<button
						type="button"
						role="menuitem"
						class="flex w-full cursor-pointer items-center gap-1.5 rounded-md border-none
							bg-transparent px-3 py-[7px] text-left text-[0.86rem] text-ink-soft transition-colors
							duration-100 hover:bg-mq-pink hover:text-mq-maroon"
						onclick={pickFitView}
					>
						<span
							class="inline-flex h-4 w-4 flex-shrink-0 items-center justify-center text-[#5a5c58]
								[&_svg]:size-[15px]">{@render icon('fit')}</span
						>
						<span class="flex-1 text-left">Fit to screen</span>
					</button>
					<button
						type="button"
						role="menuitem"
						class="flex w-full cursor-pointer items-center gap-1.5 rounded-md border-none
							bg-transparent px-3 py-[7px] text-left text-[0.86rem] text-ink-soft transition-colors
							duration-100 hover:bg-mq-pink hover:text-mq-maroon"
						onclick={pickFitSelection}
					>
						<span
							class="inline-flex h-4 w-4 flex-shrink-0 items-center justify-center text-[#5a5c58]
								[&_svg]:size-[15px]">{@render icon('fit')}</span
						>
						<span class="flex-1 text-left">Fit selection</span>
					</button>
				</div>
			{/if}
		</div>

		<button type="button" class={ICON_BTN} aria-label="Zoom in" onclick={editor.zoomIn}>
			{@render icon('zoom-in')}
		</button>
		<button type="button" class={ICON_BTN} aria-label="Fit to screen" onclick={editor.fitView}>
			{@render icon('fullscreen')}
		</button>
	</div>

	<div class="mx-1.5 h-[22px] w-px bg-line-soft"></div>

	<!-- Text formatting -->
	<div class="flex items-center gap-0.5">
		<div class="tb-menu relative">
			<button
				type="button"
				class="inline-flex h-[30px] min-w-[104px] cursor-pointer items-center gap-1.5 rounded-md
					border border-line-soft bg-transparent px-2 text-[0.82rem] text-toolbar-text
					transition-colors duration-[120ms] hover:bg-surface-hover hover:text-[#1f201d]
					[&.active]:border-mq-red [&.active]:bg-white [&.active]:text-mq-maroon"
				class:active={openDropdown === 'font'}
				aria-haspopup="menu"
				aria-expanded={openDropdown === 'font'}
				onclick={() => toggle('font')}
			>
				<span
					class="flex-1 overflow-hidden text-left text-ellipsis whitespace-nowrap"
					style="font-family: {style.fontFamily};">{style.fontFamily}</span
				>
				<span class="inline-flex h-3 w-3 text-ink-muted [&_svg]:size-3">{@render icon('chevron')}</span>
			</button>
			{#if openDropdown === 'font'}
				<div
					class="absolute top-[calc(100%+6px)] left-0 z-[100] flex max-h-[320px] min-w-[180px]
						flex-col gap-px overflow-y-auto rounded-[10px] border border-line-dropdown bg-white p-1.5
						shadow-[0_12px_28px_rgba(0,0,0,0.14)]"
					role="menu"
				>
					{#each FONT_FAMILIES as family}
						<button
							type="button"
							role="menuitem"
							class="flex w-full cursor-pointer items-center gap-1.5 rounded-md border-none
								bg-transparent px-3 py-[7px] text-left text-[0.86rem] text-ink-soft transition-colors
								duration-100 hover:bg-mq-pink hover:text-mq-maroon [&.checked]:bg-mq-pink
								[&.checked]:text-mq-maroon"
							class:checked={family === style.fontFamily}
							onclick={() => pickFont(family)}
						>
							<span
								class="inline-flex h-4 w-4 flex-shrink-0 items-center justify-center text-mq-maroon
									[&_svg]:size-3.5"
							>
								{#if family === style.fontFamily}{@render icon('check')}{/if}
							</span>
							<span class="flex-1 text-left" style="font-family: {family};">{family}</span>
						</button>
					{/each}
				</div>
			{/if}
		</div>

		<div class="tb-menu relative">
			<div
				class="group inline-flex h-[30px] min-w-[56px] items-center rounded-md border border-line-soft
					bg-transparent pr-0.5 pl-2 transition-colors duration-[120ms] hover:bg-surface-hover
					focus-within:border-mq-red focus-within:bg-white [&.active]:border-mq-red [&.active]:bg-white"
				class:active={openDropdown === 'size'}
			>
				<input
					class="w-0 min-w-[26px] flex-1 border-none bg-transparent p-0 text-right text-[0.82rem]
						tabular-nums text-toolbar-text outline-none [appearance:textfield]
						group-focus-within:text-[#1f201d]
						[&::-webkit-inner-spin-button]:appearance-none [&::-webkit-outer-spin-button]:appearance-none"
					type="text"
					inputmode="numeric"
					aria-label="Font size"
					value={sizeDraft ?? `${style.fontSize}`}
					oninput={(e) => (sizeDraft = e.currentTarget.value)}
					onfocus={(e) => focusNumber(e, (v) => (sizeDraft = v), style.fontSize)}
					onblur={commitSize}
					onkeydown={(e) => onNumberKeydown(e, commitSize, () => (sizeDraft = null))}
				/>
				<span class="pointer-events-none mr-px ml-0.5 text-[0.82rem] text-ink-muted">pt</span>
				<button
					type="button"
					class="inline-flex h-full w-4 cursor-pointer items-center justify-center border-none
						bg-transparent p-0 text-ink-muted hover:text-toolbar-text [&_svg]:size-3"
					aria-label="Font size presets"
					aria-haspopup="menu"
					aria-expanded={openDropdown === 'size'}
					onclick={() => toggle('size')}
				>
					{@render icon('chevron')}
				</button>
			</div>
			{#if openDropdown === 'size'}
				<div
					class="absolute top-[calc(100%+6px)] left-0 z-[100] flex max-h-[320px] min-w-[120px] flex-col
						gap-px overflow-y-auto rounded-[10px] border border-line-dropdown bg-white p-1.5
						shadow-[0_12px_28px_rgba(0,0,0,0.14)]"
					role="menu"
				>
					{#each FONT_SIZES as size}
						<button
							type="button"
							role="menuitem"
							class="flex w-full cursor-pointer items-center gap-1.5 rounded-md border-none
								bg-transparent px-3 py-[7px] text-left text-[0.86rem] text-ink-soft transition-colors
								duration-100 hover:bg-mq-pink hover:text-mq-maroon [&.checked]:bg-mq-pink
								[&.checked]:text-mq-maroon"
							class:checked={size === style.fontSize}
							onclick={() => pickSize(size)}
						>
							<span
								class="inline-flex h-4 w-4 flex-shrink-0 items-center justify-center text-mq-maroon
									[&_svg]:size-3.5"
							>
								{#if size === style.fontSize}{@render icon('check')}{/if}
							</span>
							<span class="flex-1 text-left tabular-nums">{size} pt</span>
						</button>
					{/each}
				</div>
			{/if}
		</div>

		<button
			type="button"
			class={FMT_BTN}
			class:toggled={style.bold}
			aria-label="Bold"
			data-tip="Bold (Ctrl+B)"
			aria-pressed={style.bold}
			onclick={() => editor.applyStyle({ bold: !style.bold })}
		>
			<span class="text-[0.95rem] leading-none font-bold">B</span>
		</button>
		<button
			type="button"
			class={FMT_BTN}
			class:toggled={style.italic}
			aria-label="Italic"
			data-tip="Italic (Ctrl+I)"
			aria-pressed={style.italic}
			onclick={() => editor.applyStyle({ italic: !style.italic })}
		>
			<span class="text-[0.95rem] leading-none font-semibold italic [font-family:Georgia,serif]">I</span>
		</button>
		<button
			type="button"
			class={FMT_BTN}
			class:toggled={style.underline}
			aria-label="Underline"
			data-tip="Underline (Ctrl+U)"
			aria-pressed={style.underline}
			onclick={() => editor.applyStyle({ underline: !style.underline })}
		>
			<span class="text-[0.95rem] leading-none font-semibold underline">U</span>
		</button>

		<label class="{FMT_BTN} flex-col gap-px" aria-label="Text color" data-tip="Text color">
			<span class="text-[0.9rem] leading-none font-bold">A</span>
			<span class="h-[3px] w-4 rounded-[1px]" style="background: {swatchColor};"></span>
			<input
				class="absolute inset-0 h-full w-full cursor-pointer border-none p-0 opacity-0"
				type="color"
				value={swatchColor}
				oninput={onTextColorInput}
				onchange={() => (liveTextColor = null)}
			/>
		</label>
	</div>

	<div class="mx-1.5 h-[22px] w-px bg-line-soft"></div>

	<!-- Object -->
	<div class="flex items-center gap-0.5">
		<button
			type="button"
			class={ICON_BTN}
			class:toggled={editor.state.locked}
			aria-label={editor.state.locked ? 'Unlock canvas' : 'Lock canvas'}
			aria-pressed={editor.state.locked}
			onclick={editor.toggleLock}
		>
			{@render icon(editor.state.locked ? 'lock-closed' : 'lock-open')}
		</button>
		<button type="button" class={ICON_BTN} aria-label="Copy" onclick={editor.copy}>
			{@render icon('copy')}
		</button>
		<button type="button" class={ICON_BTN} aria-label="Delete" onclick={editor.deleteSelected}>
			{@render icon('delete')}
		</button>
	</div>
</div>

<style>
	/*
	 * Hover tooltip — the ONLY thing kept as scoped CSS in this file. A
	 * pseudo-element whose text comes from `content: attr(...)` can't be a
	 * Tailwind utility: Tailwind's `content` support routes through a
	 * `--tw-content` custom property (initial value ""), which wins over the
	 * arbitrary `attr()` and leaves the tooltip empty. `.tb-tip` reads
	 * aria-label (icon buttons); `.tb-tip-data` reads data-tip (B/I/U/color).
	 * Everything else in the toolbar is Tailwind. The host buttons are already
	 * `relative` via ICON_BTN / FMT_BTN, so the absolute tip anchors to them.
	 */
	.tb-tip::after,
	.tb-tip-data::after {
		position: absolute;
		top: calc(100% + 7px);
		left: 50%;
		transform: translateX(-50%);
		background: #373a36;
		color: #fff;
		font-family: system-ui, -apple-system, sans-serif;
		font-size: 0.72rem;
		font-weight: 500;
		padding: 4px 8px;
		border-radius: 4px;
		white-space: nowrap;
		z-index: 200;
		pointer-events: none;
		opacity: 0;
		transition: opacity 0.12s ease;
	}
	.tb-tip::after {
		content: attr(aria-label);
	}
	.tb-tip-data::after {
		content: attr(data-tip);
	}
	.tb-tip:hover::after,
	.tb-tip-data:hover::after {
		opacity: 1;
		transition-delay: 0.45s;
	}
</style>

// client-next/src/lib/components/ToolBar.tsx
'use client';

import { useEffect, useState } from 'react';
import { FolderOpen, Save } from 'lucide-react';
import UiIcon from '@/lib/components/icons/UiIcon';
import { FONT_FAMILIES } from '@/lib/fonts';
import { MAX_ZOOM_PERCENT, MIN_ZOOM_PERCENT, ZOOM_PRESETS } from '@/lib/flow/zoom';
import { useEditor } from '@/lib/flow/EditorContext';

const FONT_SIZES = [8, 9, 10, 11, 12, 14, 16, 18, 24, 36, 48, 64];
const SIZE_MIN = 1;
const SIZE_MAX = 96;

const clamp = (n: number, min: number, max: number) => Math.min(max, Math.max(min, n));

const ICON_BTN =
  'tb-tip relative inline-flex h-8 w-8 cursor-pointer items-center justify-center rounded-md border ' +
  'border-transparent bg-transparent p-0 text-toolbar-text transition-colors duration-[120ms] ' +
  '[&_svg]:size-[18px] enabled:hover:bg-surface-hover enabled:hover:text-[#1f201d] ' +
  'disabled:cursor-not-allowed disabled:opacity-[0.32] [&.toggled]:bg-mq-pink [&.toggled]:text-mq-red';
const FMT_BTN =
  'tb-tip-data relative inline-flex h-8 w-8 cursor-pointer items-center justify-center rounded-md border ' +
  'border-transparent bg-transparent p-0 text-toolbar-text transition-colors duration-[120ms] ' +
  'hover:bg-surface-hover hover:text-[#1f201d] [&.toggled]:bg-mq-pink [&.toggled]:text-mq-red';

function icon(name: string) {
  return <UiIcon name={name} strokeWidth={1.8} />;
}

export default function ToolBar() {
  const editor = useEditor();

  const [openDropdown, setOpenDropdown] = useState<'zoom' | 'font' | 'size' | null>(null);
  const [zoomDraft, setZoomDraft] = useState<string | null>(null);
  const [sizeDraft, setSizeDraft] = useState<string | null>(null);
  const [liveTextColor, setLiveTextColor] = useState<string | null>(null);

  const toggle = (name: 'zoom' | 'font' | 'size') =>
    setOpenDropdown((cur) => (cur === name ? null : name));
  const closeDropdowns = () => setOpenDropdown(null);

  const style = editor.nodeStyle ?? {
    fontFamily: 'Inter',
    fontSize: 14,
    bold: false,
    italic: false,
    underline: false,
    textColor: '#2c2c2a',
  };
  const swatchColor = liveTextColor ?? style.textColor;

  // Drop any live preview the moment neither font nor size dropdown is open.
  useEffect(() => {
    if (openDropdown !== 'font' && openDropdown !== 'size') editor.endPreview();
  }, [openDropdown, editor]);

  useEffect(() => {
    const onPointer = (event: PointerEvent) => {
      const target = event.target as HTMLElement | null;
      if (target?.closest('.tb-menu')) return;
      closeDropdowns();
    };
    const onKey = (event: KeyboardEvent) => {
      if (event.key === 'Escape') closeDropdowns();
    };
    window.addEventListener('pointerdown', onPointer);
    window.addEventListener('keydown', onKey);
    return () => {
      window.removeEventListener('pointerdown', onPointer);
      window.removeEventListener('keydown', onKey);
    };
  }, []);

  function pickZoom(percent: number) {
    editor.setZoom(percent);
    closeDropdowns();
  }
  function pickFont(family: string) {
    editor.applyStyle({ fontFamily: family });
    closeDropdowns();
  }
  function pickSize(size: number) {
    editor.applyStyle({ fontSize: size });
    closeDropdowns();
  }

  function commitZoom() {
    if (zoomDraft !== null) {
      const n = parseInt(zoomDraft, 10);
      if (!Number.isNaN(n)) editor.setZoom(clamp(n, MIN_ZOOM_PERCENT, MAX_ZOOM_PERCENT));
    }
    setZoomDraft(null);
  }
  function commitSize() {
    if (sizeDraft !== null) {
      const n = parseInt(sizeDraft, 10);
      if (!Number.isNaN(n)) editor.applyStyle({ fontSize: clamp(n, SIZE_MIN, SIZE_MAX) });
    }
    setSizeDraft(null);
  }

  function onNumberKeydown(
    event: React.KeyboardEvent<HTMLInputElement>,
    commit: () => void,
    cancel: () => void,
  ) {
    event.stopPropagation();
    if (event.key === 'Enter') {
      event.preventDefault();
      commit();
      event.currentTarget.blur();
    } else if (event.key === 'Escape') {
      event.preventDefault();
      cancel();
      event.currentTarget.blur();
    }
  }

  function focusNumber(
    event: React.FocusEvent<HTMLInputElement>,
    set: (v: string) => void,
    current: number,
  ) {
    closeDropdowns();
    set(`${current}`);
    event.currentTarget.select();
  }

  function onTextColorInput(event: React.ChangeEvent<HTMLInputElement>) {
    const value = event.currentTarget.value;
    setLiveTextColor(value);
    editor.applyStyle({ textColor: value });
  }

  return (
    <div className="relative flex w-full flex-[0_0_46px] items-center gap-1 border-b border-line-soft bg-white py-0 pr-14 pl-3 [font-family:system-ui,-apple-system,sans-serif]">
      {/* File */}
      <div className="flex items-center gap-0.5">
        <button type="button" className={ICON_BTN} aria-label="Open file" onClick={editor.open}>
          <FolderOpen size={18} />
        </button>
        <button type="button" className={ICON_BTN} aria-label="Save" onClick={editor.save}>
          <Save size={18} />
        </button>
      </div>

      <div className="mx-1.5 h-[22px] w-px bg-line-soft" />

      {/* History */}
      <div className="flex items-center gap-0.5">
        <button type="button" className={ICON_BTN} aria-label="Undo" onClick={editor.undo} disabled={!editor.history.canUndo}>
          {icon('undo')}
        </button>
        <button type="button" className={ICON_BTN} aria-label="Redo" onClick={editor.redo} disabled={!editor.history.canRedo}>
          {icon('redo')}
        </button>
      </div>

      <div className="mx-1.5 h-[22px] w-px bg-line-soft" />

      {/* Zoom */}
      <div className="flex items-center gap-0.5">
        <button type="button" className={ICON_BTN} aria-label="Zoom out" onClick={editor.zoomOut}>
          {icon('zoom-out')}
        </button>

        <div className="tb-menu relative">
          <div
            className={`group inline-flex h-[30px] min-w-[64px] items-center rounded-md border border-line-soft bg-transparent pr-0.5 pl-2 transition-colors duration-[120ms] hover:bg-surface-hover focus-within:border-mq-red focus-within:bg-white [&.active]:border-mq-red [&.active]:bg-white ${openDropdown === 'zoom' ? 'active' : ''}`}
          >
            <input
              className="w-0 min-w-[26px] flex-1 border-none bg-transparent p-0 text-right text-[0.82rem] tabular-nums text-toolbar-text outline-none [appearance:textfield] group-focus-within:text-[#1f201d] [&::-webkit-inner-spin-button]:appearance-none [&::-webkit-outer-spin-button]:appearance-none"
              type="text"
              inputMode="numeric"
              aria-label="Zoom level"
              value={zoomDraft ?? `${editor.state.zoomPercent}`}
              onChange={(e) => setZoomDraft(e.currentTarget.value)}
              onFocus={(e) => focusNumber(e, setZoomDraft, editor.state.zoomPercent)}
              onBlur={commitZoom}
              onKeyDown={(e) => onNumberKeydown(e, commitZoom, () => setZoomDraft(null))}
            />
            <span className="pointer-events-none mr-px ml-0.5 text-[0.82rem] text-ink-muted">%</span>
            <button
              type="button"
              className="inline-flex h-full w-4 cursor-pointer items-center justify-center border-none bg-transparent p-0 text-ink-muted hover:text-toolbar-text [&_svg]:size-3"
              aria-label="Zoom presets"
              aria-haspopup="menu"
              aria-expanded={openDropdown === 'zoom'}
              onClick={() => toggle('zoom')}
            >
              {icon('chevron')}
            </button>
          </div>

          {openDropdown === 'zoom' && (
            <div className="absolute top-[calc(100%+6px)] left-0 z-[100] flex max-h-[320px] min-w-[180px] flex-col gap-px overflow-y-auto rounded-[10px] border border-line-dropdown bg-white p-1.5 shadow-[0_12px_28px_rgba(0,0,0,0.14)]" role="menu">
              <div className="px-3 pt-1.5 pb-1 text-[0.66rem] font-bold tracking-[0.08em] text-ink-muted">ZOOM LEVEL</div>
              {ZOOM_PRESETS.map((preset) => (
                <button
                  key={preset}
                  type="button"
                  role="menuitem"
                  className={`flex w-full cursor-pointer items-center gap-1.5 rounded-md border-none bg-transparent px-3 py-[7px] text-left text-[0.86rem] text-ink-soft transition-colors duration-100 hover:bg-mq-pink hover:text-mq-maroon [&.checked]:bg-mq-pink [&.checked]:text-mq-maroon ${preset === editor.state.zoomPercent ? 'checked' : ''}`}
                  onClick={() => pickZoom(preset)}
                >
                  <span className="inline-flex h-4 w-4 flex-shrink-0 items-center justify-center text-mq-maroon [&_svg]:size-3.5">
                    {preset === editor.state.zoomPercent && icon('check')}
                  </span>
                  <span className="flex-1 text-left tabular-nums">{preset}%</span>
                </button>
              ))}
              <div className="mx-1 my-1 h-px bg-[#e8e5de]" />
              <button
                type="button"
                role="menuitem"
                className="flex w-full cursor-pointer items-center gap-1.5 rounded-md border-none bg-transparent px-3 py-[7px] text-left text-[0.86rem] text-ink-soft transition-colors duration-100 hover:bg-mq-pink hover:text-mq-maroon"
                onClick={() => {
                  editor.fitView();
                  closeDropdowns();
                }}
              >
                <span className="inline-flex h-4 w-4 flex-shrink-0 items-center justify-center text-[#5a5c58] [&_svg]:size-[15px]">{icon('fit')}</span>
                <span className="flex-1 text-left">Fit to screen</span>
              </button>
              <button
                type="button"
                role="menuitem"
                className="flex w-full cursor-pointer items-center gap-1.5 rounded-md border-none bg-transparent px-3 py-[7px] text-left text-[0.86rem] text-ink-soft transition-colors duration-100 hover:bg-mq-pink hover:text-mq-maroon"
                onClick={() => {
                  editor.fitSelection();
                  closeDropdowns();
                }}
              >
                <span className="inline-flex h-4 w-4 flex-shrink-0 items-center justify-center text-[#5a5c58] [&_svg]:size-[15px]">{icon('fit')}</span>
                <span className="flex-1 text-left">Fit selection</span>
              </button>
            </div>
          )}
        </div>

        <button type="button" className={ICON_BTN} aria-label="Zoom in" onClick={editor.zoomIn}>
          {icon('zoom-in')}
        </button>
        <button type="button" className={ICON_BTN} aria-label="Fit to screen" onClick={editor.fitView}>
          {icon('fullscreen')}
        </button>
      </div>

      <div className="mx-1.5 h-[22px] w-px bg-line-soft" />

      {/* Text formatting */}
      <div className="flex items-center gap-0.5">
        <div className="tb-menu relative">
          <button
            type="button"
            className={`inline-flex h-[30px] min-w-[104px] cursor-pointer items-center gap-1.5 rounded-md border border-line-soft bg-transparent px-2 text-[0.82rem] text-toolbar-text transition-colors duration-[120ms] hover:bg-surface-hover hover:text-[#1f201d] [&.active]:border-mq-red [&.active]:bg-white [&.active]:text-mq-maroon ${openDropdown === 'font' ? 'active' : ''}`}
            aria-haspopup="menu"
            aria-expanded={openDropdown === 'font'}
            onClick={() => toggle('font')}
          >
            <span className="flex-1 overflow-hidden text-left text-ellipsis whitespace-nowrap" style={{ fontFamily: style.fontFamily }}>
              {style.fontFamily}
            </span>
            <span className="inline-flex h-3 w-3 text-ink-muted [&_svg]:size-3">{icon('chevron')}</span>
          </button>
          {openDropdown === 'font' && (
            <div
              className="absolute top-[calc(100%+6px)] left-0 z-[100] flex max-h-[320px] min-w-[180px] flex-col gap-px overflow-y-auto rounded-[10px] border border-line-dropdown bg-white p-1.5 shadow-[0_12px_28px_rgba(0,0,0,0.14)]"
              role="menu"
              tabIndex={-1}
              onMouseLeave={() => editor.endPreview()}
            >
              {FONT_FAMILIES.map((family) => (
                <button
                  key={family}
                  type="button"
                  role="menuitem"
                  className={`flex w-full cursor-pointer items-center gap-1.5 rounded-md border-none bg-transparent px-3 py-[7px] text-left text-[0.86rem] text-ink-soft transition-colors duration-100 hover:bg-mq-pink hover:text-mq-maroon [&.checked]:bg-mq-pink [&.checked]:text-mq-maroon ${family === style.fontFamily ? 'checked' : ''}`}
                  onClick={() => pickFont(family)}
                  onMouseEnter={() => editor.previewStyle({ fontFamily: family })}
                >
                  <span className="inline-flex h-4 w-4 flex-shrink-0 items-center justify-center text-mq-maroon [&_svg]:size-3.5">
                    {family === style.fontFamily && icon('check')}
                  </span>
                  <span className="flex-1 text-left" style={{ fontFamily: family }}>{family}</span>
                </button>
              ))}
            </div>
          )}
        </div>

        <div className="tb-menu relative">
          <div
            className={`group inline-flex h-[30px] min-w-[56px] items-center rounded-md border border-line-soft bg-transparent pr-0.5 pl-2 transition-colors duration-[120ms] hover:bg-surface-hover focus-within:border-mq-red focus-within:bg-white [&.active]:border-mq-red [&.active]:bg-white ${openDropdown === 'size' ? 'active' : ''}`}
          >
            <input
              className="w-0 min-w-[26px] flex-1 border-none bg-transparent p-0 text-right text-[0.82rem] tabular-nums text-toolbar-text outline-none [appearance:textfield] group-focus-within:text-[#1f201d] [&::-webkit-inner-spin-button]:appearance-none [&::-webkit-outer-spin-button]:appearance-none"
              type="text"
              inputMode="numeric"
              aria-label="Font size"
              value={sizeDraft ?? `${style.fontSize}`}
              onChange={(e) => setSizeDraft(e.currentTarget.value)}
              onFocus={(e) => focusNumber(e, setSizeDraft, style.fontSize)}
              onBlur={commitSize}
              onKeyDown={(e) => onNumberKeydown(e, commitSize, () => setSizeDraft(null))}
            />
            <span className="pointer-events-none mr-px ml-0.5 text-[0.82rem] text-ink-muted">pt</span>
            <button
              type="button"
              className="inline-flex h-full w-4 cursor-pointer items-center justify-center border-none bg-transparent p-0 text-ink-muted hover:text-toolbar-text [&_svg]:size-3"
              aria-label="Font size presets"
              aria-haspopup="menu"
              aria-expanded={openDropdown === 'size'}
              onClick={() => toggle('size')}
            >
              {icon('chevron')}
            </button>
          </div>
          {openDropdown === 'size' && (
            <div
              className="absolute top-[calc(100%+6px)] left-0 z-[100] flex max-h-[320px] min-w-[120px] flex-col gap-px overflow-y-auto rounded-[10px] border border-line-dropdown bg-white p-1.5 shadow-[0_12px_28px_rgba(0,0,0,0.14)]"
              role="menu"
              tabIndex={-1}
              onMouseLeave={() => editor.endPreview()}
            >
              {FONT_SIZES.map((size) => (
                <button
                  key={size}
                  type="button"
                  role="menuitem"
                  className={`flex w-full cursor-pointer items-center gap-1.5 rounded-md border-none bg-transparent px-3 py-[7px] text-left text-[0.86rem] text-ink-soft transition-colors duration-100 hover:bg-mq-pink hover:text-mq-maroon [&.checked]:bg-mq-pink [&.checked]:text-mq-maroon ${size === style.fontSize ? 'checked' : ''}`}
                  onClick={() => pickSize(size)}
                  onMouseEnter={() => editor.previewStyle({ fontSize: size })}
                >
                  <span className="inline-flex h-4 w-4 flex-shrink-0 items-center justify-center text-mq-maroon [&_svg]:size-3.5">
                    {size === style.fontSize && icon('check')}
                  </span>
                  <span className="flex-1 text-left tabular-nums">{size} pt</span>
                </button>
              ))}
            </div>
          )}
        </div>

        <button
          type="button"
          className={`${FMT_BTN} ${style.bold ? 'toggled' : ''}`}
          aria-label="Bold"
          data-tip="Bold (Ctrl+B)"
          aria-pressed={style.bold}
          onClick={() => editor.applyStyle({ bold: !style.bold })}
        >
          <span className="text-[0.95rem] leading-none font-bold">B</span>
        </button>
        <button
          type="button"
          className={`${FMT_BTN} ${style.italic ? 'toggled' : ''}`}
          aria-label="Italic"
          data-tip="Italic (Ctrl+I)"
          aria-pressed={style.italic}
          onClick={() => editor.applyStyle({ italic: !style.italic })}
        >
          <span className="text-[0.95rem] leading-none font-semibold italic [font-family:Georgia,serif]">I</span>
        </button>
        <button
          type="button"
          className={`${FMT_BTN} ${style.underline ? 'toggled' : ''}`}
          aria-label="Underline"
          data-tip="Underline (Ctrl+U)"
          aria-pressed={style.underline}
          onClick={() => editor.applyStyle({ underline: !style.underline })}
        >
          <span className="text-[0.95rem] leading-none font-semibold underline">U</span>
        </button>

        <label className={`${FMT_BTN} flex-col gap-px`} aria-label="Text color" data-tip="Text color">
          <span className="text-[0.9rem] leading-none font-bold">A</span>
          <span className="h-[3px] w-4 rounded-[1px]" style={{ background: swatchColor }} />
          <input
            className="absolute inset-0 h-full w-full cursor-pointer border-none p-0 opacity-0"
            type="color"
            value={swatchColor}
            onChange={onTextColorInput}
            onBlur={() => setLiveTextColor(null)}
          />
        </label>
      </div>

      <div className="mx-1.5 h-[22px] w-px bg-line-soft" />

      {/* Object */}
      <div className="flex items-center gap-0.5">
        <button
          type="button"
          className={`${ICON_BTN} ${editor.state.locked ? 'toggled' : ''}`}
          aria-label={editor.state.locked ? 'Unlock canvas' : 'Lock canvas'}
          aria-pressed={editor.state.locked}
          onClick={editor.toggleLock}
        >
          {icon(editor.state.locked ? 'lock-closed' : 'lock-open')}
        </button>
        <button type="button" className={ICON_BTN} aria-label="Copy" onClick={editor.copy}>
          {icon('copy')}
        </button>
        <button type="button" className={ICON_BTN} aria-label="Delete" onClick={editor.deleteSelected}>
          {icon('delete')}
        </button>
      </div>

      {/* Style-panel toggle: pinned to the toolbar's right corner. */}
      <div className="absolute top-1/2 right-3 -translate-y-1/2">
        <button
          type="button"
          className={`${ICON_BTN} ${editor.state.showStylePanel ? 'toggled' : ''}`}
          aria-label={editor.state.showStylePanel ? 'Hide style panel' : 'Show style panel'}
          aria-pressed={editor.state.showStylePanel}
          onClick={editor.toggleStylePanel}
        >
          {icon('style-panel')}
        </button>
      </div>
    </div>
  );
}
