// client/src/lib/components/sidebar/Sidebar.tsx
'use client';

import { useEffect, useState } from 'react';
import NodeContainer from './NodeContainer';
import CollapseButton from './CollapseButton';
import ResizeHandle from './ResizeHandle';
import CustomLibraries from '@/lib/node-library/CustomLibraries';
import { useSidebarStore } from '@/lib/stores/sidebar.store';
import {
  getShapesByCategory,
  type NodeShape,
  type NodeCategory,
  type PaletteGroupId,
} from '@/lib/flow/nodes/registry';

interface PaletteGroupDefinition {
  id: PaletteGroupId;
  title: string;
}
interface PaletteCategoryDefinition {
  id: NodeCategory;
  title: string;
  groups?: readonly PaletteGroupDefinition[];
}

const PALETTE_CATEGORIES: readonly PaletteCategoryDefinition[] = [
  { id: 'basic', title: 'BASIC' },
  { id: 'arrows', title: 'ARROWS' },
  { id: 'flowchart', title: 'FLOWCHART' },
  { id: 'entity-relation', title: 'ENTITY RELATION' },
  { id: 'uml', title: 'UML' },
];

export default function Sidebar() {
  const isCollapsed = useSidebarStore((s) => s.isCollapsed);
  const width = useSidebarStore((s) => s.width);
  const isResizing = useSidebarStore((s) => s.isResizing);
  const load = useSidebarStore((s) => s.load);
  const setRenderedWidth = useSidebarStore((s) => s.setRenderedWidth);

  const [searchBar, setSearchBar] = useState('');
  const [expandedCategories, setExpandedCategories] = useState<Record<NodeCategory, boolean>>(
    () => Object.fromEntries(PALETTE_CATEGORIES.map(({ id }) => [id, false])) as Record<NodeCategory, boolean>,
  );
  const [expandedGroups, setExpandedGroups] = useState<Record<string, boolean>>({});

  useEffect(() => {
    load();
  }, [load]);
  useEffect(() => {
    setRenderedWidth(isCollapsed ? 0 : width);
  }, [isCollapsed, width, setRenderedWidth]);

  const searchQuery = searchBar.trim().toLowerCase();
  const isSearching = searchQuery.length > 0;

  const groupKey = (c: NodeCategory, g: PaletteGroupId) => `${c}:${g}`;
  const toggleCategory = (c: NodeCategory) => setExpandedCategories((p) => ({ ...p, [c]: !p[c] }));
  const toggleGroup = (c: NodeCategory, g: PaletteGroupId) =>
    setExpandedGroups((p) => ({ ...p, [groupKey(c, g)]: !p[groupKey(c, g)] }));

  const filterShapes = (shapes: readonly NodeShape[]): NodeShape[] => {
    if (!searchQuery) return [...shapes];
    return shapes.filter((shape) =>
      [shape.label, ...(shape.searchAliases ?? [])].some((term) => term.toLowerCase().includes(searchQuery)),
    );
  };

  const sections = PALETTE_CATEGORIES.map((definition) => {
    const categoryShapes = getShapesByCategory(definition.id);
    const groups = (definition.groups ?? [])
      .map((group) => {
        const shapes = filterShapes(categoryShapes.filter((shape) => shape.paletteGroup === group.id));
        return {
          id: group.id,
          heading: group.title,
          shapes,
          expanded: isSearching
            ? shapes.length > 0
            : (expandedGroups[groupKey(definition.id, group.id)] ?? false),
        };
      })
      .filter((group) => (isSearching ? group.shapes.length > 0 : true));

    const shapes = definition.groups ? [] : filterShapes(categoryShapes);
    const hasVisibleContent = shapes.length > 0 || groups.length > 0;

    return {
      category: definition.id,
      title: definition.title,
      shapes,
      groups,
      expanded: isSearching ? hasVisibleContent : expandedCategories[definition.id],
    };
  }).filter((section) => (isSearching ? section.shapes.length > 0 || section.groups.length > 0 : true));

  return (
    <aside
      className={`absolute top-[0.2%] bottom-0 left-0 z-40 m-0 rounded-none border-l-0 bg-panel ${
        isResizing ? '' : 'transition-[width] duration-150'
      } ${isCollapsed ? 'shadow-none' : 'shadow-[0_0_10px_#c4c1b8]'}`}
      style={{ width: isCollapsed ? 0 : width }}
    >
      <div
        className={`flex h-full w-full flex-col gap-[1.4em] overflow-x-hidden overflow-y-auto px-[1.2em] pt-[2.5em] pb-[1em] ${
          isCollapsed ? 'invisible' : ''
        }`}
        aria-hidden={isCollapsed}
      >
        <div className="flex h-9 items-center rounded-lg border border-line bg-white px-2.5 focus-within:border-mq-red">
          <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={1.8} strokeLinecap="round" strokeLinejoin="round" className="size-4 shrink-0 text-ink-muted">
            <circle cx="11" cy="11" r="7" />
            <line x1="20" y1="20" x2="16.5" y2="16.5" />
          </svg>
          <input
            className="min-w-0 flex-1 appearance-none border-none bg-transparent px-2 text-[0.9rem] text-ink-soft outline-none placeholder:text-ink-muted"
            value={searchBar}
            onChange={(e) => setSearchBar(e.target.value)}
            placeholder="Search shapes"
          />
        </div>

        {sections.map((section) => (
          <NodeContainer
            key={section.category}
            heading={section.title}
            shapes={section.shapes}
            groups={section.groups}
            expanded={section.expanded}
            onToggle={() => toggleCategory(section.category)}
            onGroupToggle={(group) => toggleGroup(section.category, group)}
          />
        ))}
        <CustomLibraries searchQuery={searchQuery} />
      </div>

      <CollapseButton />
      {!isCollapsed && <ResizeHandle />}
    </aside>
  );
}

// frontend/src/lib/components/Sidebar.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import NodeContainer from '$lib/components/NodeContainer.svelte';
	import CollapseButton from '$lib/components/sidebar/CollapseButton.svelte';
	import ResizeHandle from '$lib/components/sidebar/ResizeHandle.svelte';
	import { loadSidebarStateFromStorage, sidebarState } from '$lib/stores/sidebar.store.svelte';
	import {
		getShapesByCategory,
		type NodeShape,
		type NodeCategory
	} from '$lib/flow/nodes/registry';

	let searchBar = $state('');

	// Fixed display order — every palette category is always visible so the
	// user can see the full taxonomy (BASIC / ARROWS / ENTITY RELATION / UML)
	// even before shapes have been authored for each one.
	const CATEGORY_ORDER: NodeCategory[] = ['basic', 'arrows', 'flowchart', 'entity-relation', 'uml'];

	// Stable display titles per category. Add new entries here when a new
	// NodeCategory is introduced — kept beside the iteration so additions are
	// one line, not a fan-out across the template.
	const CATEGORY_TITLES: Record<NodeCategory, string> = {
		basic: 'BASIC',
		arrows: 'ARROWS',
		flowchart: 'FLOWCHART',
		'entity-relation': 'ENTITY RELATION',
		uml: 'UML'
	};

	// Per-category expand/collapse state. Default to all collapsed so the
	// palette opens in the compact dropdown-list form.
	let expandedCategories = $state<Record<NodeCategory, boolean>>({
		basic: false,
		arrows: false,
		flowchart: false,
		'entity-relation': false,
		uml: false
	});

	function toggleCategory(category: NodeCategory) {
		expandedCategories[category] = !expandedCategories[category];
	}

	function filterShapes(shapes: NodeShape[]): NodeShape[] {
		const query = searchBar.trim().toLowerCase();
		if (!query) return shapes;
		return shapes.filter((s) => s.label.toLowerCase().includes(query));
	}

	const isSearching = $derived(searchBar.trim().length > 0);

	// Sections in fixed order. While searching, only sections with matches
	// are shown and they auto-expand so results are immediately visible.
	const sections = $derived(
		CATEGORY_ORDER.map((category) => {
			const shapes = filterShapes(getShapesByCategory(category));
			return {
				category,
				title: CATEGORY_TITLES[category],
				shapes,
				expanded: isSearching ? shapes.length > 0 : expandedCategories[category]
			};
		}).filter((section) => (isSearching ? section.shapes.length > 0 : true))
	);

	onMount(() => {
		loadSidebarStateFromStorage();
	});
</script>

<!-- Width transition ONLY while not dragging: collapse/expand still animates,
     but a live resize tracks the cursor 1:1 — with the 150ms ease always on,
     the edge kept chasing the pointer and the drag felt rubbery. -->
<aside
	class="absolute top-[0.2%] bottom-0 left-0 m-0 rounded-none border-l-0 bg-panel {sidebarState.isResizing
		? ''
		: 'transition-[width] duration-150'} {sidebarState.isCollapsed
		? 'shadow-none'
		: 'shadow-[0_0_10px_#c4c1b8]'}"
	style:width={sidebarState.isCollapsed ? '0px' : `${sidebarState.width}px`}
>
	<div
		class="flex h-full w-full flex-col gap-[1.4em] overflow-x-hidden overflow-y-auto px-[1.2em] pt-[2.5em] pb-[1em] {sidebarState.isCollapsed
			? 'invisible'
			: ''}"
		aria-hidden={sidebarState.isCollapsed}
	>
		<div
			class="flex h-9 items-center rounded-lg border border-line bg-white px-2.5
				focus-within:border-mq-red"
		>
			<svg
				viewBox="0 0 24 24"
				fill="none"
				stroke="currentColor"
				stroke-width="1.8"
				stroke-linecap="round"
				stroke-linejoin="round"
				class="size-4 shrink-0 text-ink-muted"
			>
				<circle cx="11" cy="11" r="7" />
				<line x1="20" y1="20" x2="16.5" y2="16.5" />
			</svg>
			<input
				class="min-w-0 flex-1 appearance-none border-none bg-transparent px-2 text-[0.9rem]
					text-ink-soft outline-none placeholder:text-ink-muted"
				bind:value={searchBar}
				placeholder="Search shapes"
			/>
		</div>

		{#each sections as section (section.category)}
			<NodeContainer
				heading={section.title}
				shapes={section.shapes}
				expanded={section.expanded}
				onToggle={() => toggleCategory(section.category)}
			/>
		{/each}
	</div>

	<CollapseButton />
	{#if !sidebarState.isCollapsed}
		<ResizeHandle />
	{/if}
</aside>
