// src/lib/components/menubar/MenuBar.svelte
<script lang="ts">
	import { getContext, onMount } from 'svelte';
	import { editorMetaData } from '$lib/stores/editor.store.svelte';
	import type { Exporter } from '$lib/exporters';

	interface MenuItem {
		type?: 'divider';
		icon?: string;
		label?: string;
		shortcut?: string;
		disabled?: boolean;
		danger?: boolean;
		toggle?: boolean;
		checked?: boolean;
		submenu?: MenuItem[];
		onClick?: () => void;
	}

	interface EditorContext {
		state: { zoomPercent: number; showGrid: boolean; snapToGrid: boolean };
		history: { canUndo: boolean; canRedo: boolean };
		save: () => void;
		newFile: () => void;
		open: () => void;
		saveAs: () => void;
		exportFormats: readonly Exporter[];
		exportAs: (formatId: string) => void;
		undo: () => void;
		redo: () => void;
		cut: () => void;
		copy: () => void;
		paste: () => void;
		zoomIn: () => void;
		zoomOut: () => void;
		fitView: () => void;
		duplicate: () => void;
		deleteSelected: () => void;
		selectAll: () => void;
		bringToFront: () => void;
		sendToBack: () => void;
		group: () => void;
		ungroup: () => void;
		toggleShowGrid: () => void;
		toggleSnapToGrid: () => void;
		share: () => void;
	}

	const editor = getContext<EditorContext>('editor');

	const USER_INITIALS = 'MD';

	let openMenu: string | null = $state(null);
	let openSubmenu: string | null = $state(null);

	function toggleMenu(label: string) {
		openMenu = openMenu === label ? null : label;
		openSubmenu = null;
	}

	function closeMenus() {
		openMenu = null;
		openSubmenu = null;
	}

	function runItem(item: MenuItem) {
		if (item.disabled) return;
		if (item.submenu) {
			openSubmenu = openSubmenu === item.label ? null : (item.label ?? null);
			return;
		}
		if (!item.onClick) return;
		item.onClick();
		closeMenus();
	}

	// Outside click + Escape close any open dropdown / submenu.
	onMount(() => {
		const onPointer = (event: PointerEvent) => {
			const target = event.target as HTMLElement | null;
			if (target?.closest('.menu-bar .menus')) return;
			closeMenus();
		};
		const onKey = (event: KeyboardEvent) => {
			if (event.key === 'Escape') closeMenus();
		};
		window.addEventListener('pointerdown', onPointer);
		window.addEventListener('keydown', onKey);
		return () => {
			window.removeEventListener('pointerdown', onPointer);
			window.removeEventListener('keydown', onKey);
		};
	});

	// Export submenu built off the registry so new formats appear automatically.
	// Format label gets its extension appended in parens (e.g. "XML (.easydraw)").
	const exportSubmenu: MenuItem[] = $derived(
		editor.exportFormats.map((format) => ({
			label: `${format.label} (${format.extension})`,
			onClick: () => editor.exportAs(format.id)
		}))
	);

	// Menus rebuild each render so disabled/checked state stays in sync with state/history.
	const menus = $derived<Record<string, MenuItem[]>>({
		File: [
			{ icon: 'new', label: 'New', shortcut: 'Ctrl+N', onClick: editor.newFile },
			{ icon: 'open', label: 'Open…', shortcut: 'Ctrl+O', onClick: editor.open },
			{ icon: 'save', label: 'Save', shortcut: 'Ctrl+S', onClick: editor.save },
			{ icon: 'save', label: 'Save As…', shortcut: 'Ctrl+Shift+S', onClick: editor.saveAs },
			{ type: 'divider' },
			{ icon: 'export', label: 'Export as', submenu: exportSubmenu }
		],
		Edit: [
			{
				icon: 'undo',
				label: 'Undo',
				shortcut: 'Ctrl+Z',
				onClick: editor.undo,
				disabled: !editor.history.canUndo
			},
			{
				icon: 'redo',
				label: 'Redo',
				shortcut: 'Ctrl+Y',
				onClick: editor.redo,
				disabled: !editor.history.canRedo
			},
			{ type: 'divider' },
			{ icon: 'cut', label: 'Cut', shortcut: 'Ctrl+X', onClick: editor.cut },
			{ icon: 'copy', label: 'Copy', shortcut: 'Ctrl+C', onClick: editor.copy },
			{ icon: 'paste', label: 'Paste', shortcut: 'Ctrl+V', onClick: editor.paste },
			{
				icon: 'duplicate',
				label: 'Duplicate',
				shortcut: 'Ctrl+D',
				onClick: editor.duplicate
			},
			{ type: 'divider' },
			{
				icon: 'select-all',
				label: 'Select all',
				shortcut: 'Ctrl+A',
				onClick: editor.selectAll
			},
			{ type: 'divider' },
			{
				icon: 'delete',
				label: 'Delete',
				shortcut: 'Del',
				onClick: editor.deleteSelected,
				danger: true
			}
		],
		View: [
			{
				toggle: true,
				label: 'Show grid',
				checked: editor.state.showGrid,
				onClick: editor.toggleShowGrid
			},
			{
				toggle: true,
				label: 'Snap to grid',
				checked: editor.state.snapToGrid,
				onClick: editor.toggleSnapToGrid
			},
			{ type: 'divider' },
			{ icon: 'zoom-in', label: 'Zoom in', shortcut: 'Ctrl+=', onClick: editor.zoomIn },
			{ icon: 'zoom-out', label: 'Zoom out', shortcut: 'Ctrl+-', onClick: editor.zoomOut },
			{
				icon: 'fit',
				label: 'Fit to screen',
				shortcut: 'Ctrl+Shift+H',
				onClick: editor.fitView
			}
		],
		Arrange: [
			{
				icon: 'bring-front',
				label: 'Bring to front',
				shortcut: 'Ctrl+Shift+F',
				onClick: editor.bringToFront
			},
			{
				icon: 'send-back',
				label: 'Send to back',
				shortcut: 'Ctrl+Shift+B',
				onClick: editor.sendToBack
			},
			{ type: 'divider' },
			{ icon: 'group', label: 'Group', shortcut: 'Ctrl+G', onClick: editor.group },
			{ icon: 'ungroup', label: 'Ungroup', shortcut: 'Ctrl+Shift+G', onClick: editor.ungroup }
		],
		Help: [
			{
				icon: 'info',
				label: 'About EasyDraw',
				onClick: () => alert('EasyDraw — a free diagram editor.')
			},
			{
				icon: 'keyboard',
				label: 'Keyboard shortcuts',
				onClick: () =>
					alert(
						'Save: Ctrl+S\nSave As: Ctrl+Shift+S\nOpen: Ctrl+O\nNew: Ctrl+N\nUndo: Ctrl+Z\nRedo: Ctrl+Y\nCut: Ctrl+X\nCopy: Ctrl+C\nPaste: Ctrl+V\nDuplicate: Ctrl+D\nSelect All: Ctrl+A\nDelete: Del\nGroup: Ctrl+G\nUngroup: Ctrl+Shift+G\nBring to Front: Ctrl+Shift+F\nSend to Back: Ctrl+Shift+B\nZoom In: Ctrl+=\nZoom Out: Ctrl+-\nFit to Screen: Ctrl+Shift+H'
					)
			}
		]
	});

	const menuLabels = ['File', 'Edit', 'View', 'Arrange', 'Help'];
</script>

{#snippet menuIcon(name: string)}
	<svg
		viewBox="0 0 24 24"
		class="item-icon"
		fill="none"
		stroke="currentColor"
		stroke-width="1.7"
		stroke-linecap="round"
		stroke-linejoin="round"
	>
		{#if name === 'new'}
			<path d="M14 3v5h5" />
			<path d="M5 3h9l5 5v13a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2z" />
			<line x1="12" y1="12" x2="12" y2="18" />
			<line x1="9" y1="15" x2="15" y2="15" />
		{:else if name === 'open'}
			<path d="M3 7a2 2 0 0 1 2-2h4l2 2h8a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V7z" />
		{:else if name === 'save'}
			<path d="M19 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h11l5 5v11a2 2 0 0 1-2 2z" />
		{:else if name === 'export'}
			<path d="M12 14V3" />
			<polyline points="8 7 12 3 16 7" />
			<path d="M5 17v2a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2v-2" />
		{:else if name === 'undo'}
			<polyline points="9 14 4 9 9 4" />
			<path d="M4 9h11a5 5 0 0 1 5 5v0a5 5 0 0 1-5 5h-4" />
		{:else if name === 'redo'}
			<polyline points="15 14 20 9 15 4" />
			<path d="M20 9H9a5 5 0 0 0-5 5v0a5 5 0 0 0 5 5h4" />
		{:else if name === 'cut'}
			<circle cx="6" cy="6" r="3" />
			<circle cx="6" cy="18" r="3" />
			<line x1="20" y1="4" x2="8.12" y2="15.88" />
			<line x1="14.47" y1="14.48" x2="20" y2="20" />
			<line x1="8.12" y1="8.12" x2="12" y2="12" />
		{:else if name === 'duplicate'}
			<rect x="9" y="9" width="11" height="11" rx="2" />
			<path d="M5 15H4a1 1 0 0 1-1-1V4a1 1 0 0 1 1-1h10a1 1 0 0 1 1 1v1" />
			<line x1="12" y1="12" x2="17" y2="12" />
			<line x1="14.5" y1="9.5" x2="14.5" y2="14.5" />
		{:else if name === 'copy'}
			<rect x="9" y="9" width="11" height="11" rx="2" />
			<path d="M5 15H4a1 1 0 0 1-1-1V4a1 1 0 0 1 1-1h10a1 1 0 0 1 1 1v1" />
		{:else if name === 'paste'}
			<rect x="8" y="3" width="8" height="3" rx="1" />
			<path d="M16 5h2a2 2 0 0 1 2 2v13a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V7a2 2 0 0 1 2-2h2" />
		{:else if name === 'select-all'}
			<rect x="4" y="4" width="16" height="16" rx="1" stroke-dasharray="2 3" />
			<line x1="9" y1="12" x2="15" y2="12" />
			<line x1="12" y1="9" x2="12" y2="15" />
		{:else if name === 'delete'}
			<polyline points="3 6 5 6 21 6" />
			<path d="M19 6l-1 14a2 2 0 0 1-2 2H8a2 2 0 0 1-2-2L5 6" />
			<path d="M10 11v6" />
			<path d="M14 11v6" />
			<path d="M9 6V4a1 1 0 0 1 1-1h4a1 1 0 0 1 1 1v2" />
		{:else if name === 'check'}
			<polyline points="5 12 10 17 19 8" />
		{:else if name === 'zoom-in'}
			<circle cx="11" cy="11" r="7" />
			<line x1="20" y1="20" x2="16" y2="16" />
			<line x1="11" y1="8" x2="11" y2="14" />
			<line x1="8" y1="11" x2="14" y2="11" />
		{:else if name === 'zoom-out'}
			<circle cx="11" cy="11" r="7" />
			<line x1="20" y1="20" x2="16" y2="16" />
			<line x1="8" y1="11" x2="14" y2="11" />
		{:else if name === 'fit'}
			<polyline points="4 9 4 4 9 4" />
			<polyline points="20 9 20 4 15 4" />
			<polyline points="4 15 4 20 9 20" />
			<polyline points="20 15 20 20 15 20" />
		{:else if name === 'bring-front'}
			<path d="M12 3l9 4-9 4-9-4 9-4z" />
			<path d="M3 12l9 4 9-4" />
			<path d="M3 17l9 4 9-4" opacity="0.45" />
		{:else if name === 'send-back'}
			<path d="M3 7l9-4 9 4-9 4-9-4z" opacity="0.45" />
			<path d="M3 12l9 4 9-4" opacity="0.7" />
			<path d="M3 17l9 4 9-4" />
		{:else if name === 'group'}
			<rect x="3" y="3" width="11" height="11" rx="1.5" />
			<rect x="10" y="10" width="11" height="11" rx="1.5" />
		{:else if name === 'ungroup'}
			<rect x="3" y="3" width="9" height="9" rx="1" stroke-dasharray="2 2" />
			<rect x="12" y="12" width="9" height="9" rx="1" stroke-dasharray="2 2" />
		{:else if name === 'info'}
			<circle cx="12" cy="12" r="9" />
			<line x1="12" y1="8" x2="12" y2="8" />
			<line x1="12" y1="11" x2="12" y2="16" />
		{:else if name === 'keyboard'}
			<rect x="2" y="6" width="20" height="12" rx="2" />
			<line x1="6" y1="10" x2="6" y2="10" />
			<line x1="10" y1="10" x2="10" y2="10" />
			<line x1="14" y1="10" x2="14" y2="10" />
			<line x1="18" y1="10" x2="18" y2="10" />
			<line x1="7" y1="14" x2="17" y2="14" />
		{:else if name === 'chevron-right'}
			<polyline points="9 6 15 12 9 18" />
		{/if}
	</svg>
{/snippet}

<header class="menu-bar">
	<div class="brand-icon" aria-label="EasyDraw">
		<svg viewBox="0 0 24 24" fill="none" aria-hidden="true">
			<rect x="3" y="3" width="8" height="8" rx="2" fill="#ffffff" />
			<rect x="13" y="13" width="8" height="8" rx="2" fill="#ffffff" />
			<path d="M11 7h4a2 2 0 0 1 2 2v4" stroke="#ffffff" stroke-width="1.8" />
		</svg>
	</div>

	<input
		class="file-name"
		bind:value={editorMetaData.fileName}
		aria-label="Document file name"
		placeholder="Untitled"
	/>

	<span class="status-badge"><span class="status-dot"></span>Draft</span>

	<nav class="menus">
		{#each menuLabels as label}
			<div class="menu-wrapper">
				<button
					class="menu-trigger"
					class:active={openMenu === label}
					type="button"
					aria-haspopup="menu"
					aria-expanded={openMenu === label}
					onclick={() => toggleMenu(label)}
				>
					{label}
				</button>
				{#if openMenu === label}
					<div class="dropdown" role="menu">
						{#each menus[label] as item}
							{#if item.type === 'divider'}
								<div class="dropdown-divider" role="separator"></div>
							{:else}
								<div class="item-wrapper">
									<button
										type="button"
										role="menuitem"
										class="dropdown-item"
										class:danger={item.danger}
										class:has-submenu={!!item.submenu}
										class:active={item.submenu && openSubmenu === item.label}
										disabled={item.disabled}
										onclick={() => runItem(item)}
									>
										<span class="item-icon-wrap">
											{#if item.toggle}
												{#if item.checked}
													{@render menuIcon('check')}
												{/if}
											{:else if item.icon}
												{@render menuIcon(item.icon)}
											{/if}
										</span>
										<span class="item-label">{item.label}</span>
										{#if item.shortcut}
											<span class="item-shortcut">{item.shortcut}</span>
										{:else if item.submenu}
											<span class="item-chevron"
												>{@render menuIcon('chevron-right')}</span
											>
										{/if}
									</button>
									{#if item.submenu && openSubmenu === item.label}
										<div class="dropdown submenu" role="menu">
											{#each item.submenu as sub}
												<button
													type="button"
													role="menuitem"
													class="dropdown-item"
													disabled={sub.disabled}
													onclick={() => runItem(sub)}
												>
													<span class="item-icon-wrap"></span>
													<span class="item-label">{sub.label}</span>
													{#if sub.shortcut}
														<span class="item-shortcut"
															>{sub.shortcut}</span
														>
													{/if}
												</button>
											{/each}
										</div>
									{/if}
								</div>
							{/if}
						{/each}
					</div>
				{/if}
			</div>
		{/each}
	</nav>

	<div class="spacer"></div>

	<div class="right-cluster">
		<button type="button" class="hbtn" aria-label="Collaborators">
			<svg
				viewBox="0 0 24 24"
				fill="none"
				stroke="currentColor"
				stroke-width="1.7"
				stroke-linecap="round"
				stroke-linejoin="round"
			>
				<circle cx="9" cy="8" r="3" />
				<path d="M3 20c0-3 2.7-5 6-5s6 2 6 5" />
				<path d="M16 4a3 3 0 0 1 0 6" />
				<path d="M17.5 14c2.2.4 3.5 2 3.5 4" />
			</svg>
		</button>

		<div class="avatar">{USER_INITIALS}</div>

		<button type="button" class="hbtn" aria-label="Present">
			<svg
				viewBox="0 0 24 24"
				fill="none"
				stroke="currentColor"
				stroke-width="1.7"
				stroke-linecap="round"
				stroke-linejoin="round"
			>
				<path d="M8 5v14l11-7z" />
			</svg>
		</button>

		<button type="button" class="share-btn" onclick={editor.share}>
			<svg
				viewBox="0 0 24 24"
				fill="none"
				stroke="currentColor"
				stroke-width="1.7"
				stroke-linecap="round"
				stroke-linejoin="round"
			>
				<path d="M22 2 11 13" />
				<path d="M22 2 15 22l-4-9-9-4 20-7z" />
			</svg>
			Share
		</button>

		<button type="button" class="hbtn" aria-label="Copy link" onclick={editor.share}>
			<svg
				viewBox="0 0 24 24"
				fill="none"
				stroke="currentColor"
				stroke-width="1.7"
				stroke-linecap="round"
				stroke-linejoin="round"
			>
				<path d="M10 13a5 5 0 0 0 7 0l3-3a5 5 0 0 0-7-7l-1.5 1.5" />
				<path d="M14 11a5 5 0 0 0-7 0l-3 3a5 5 0 0 0 7 7l1.5-1.5" />
			</svg>
		</button>
	</div>
</header>

<style>
	.menu-bar {
		display: flex;
		align-items: center;
		gap: 0.4rem;
		padding: 0 0.85rem;
		height: 52px;
		background: #76232f;
		color: white;
		font-family:
			system-ui,
			-apple-system,
			sans-serif;
	}

	.menus {
		display: flex;
		gap: 0.1rem;
		margin-left: 0.5rem;
	}

	.spacer {
		flex: 1 1 auto;
	}

	.brand-icon {
		width: 30px;
		height: 30px;
		flex-shrink: 0;
		background: #a6192e;
		display: flex;
		align-items: center;
		justify-content: center;
		border-radius: 7px;
	}

	.brand-icon svg {
		width: 18px;
		height: 18px;
	}

	.file-name {
		background: transparent;
		border: 1px solid transparent;
		color: white;
		font-weight: 700;
		font-size: 0.95rem;
		font-family: inherit;
		padding: 0.25rem 0.5rem;
		border-radius: 6px;
		min-width: 6rem;
		max-width: 18rem;
		transition:
			background 0.15s ease,
			border-color 0.15s ease;
	}

	/* "Draft" status pill: faint translucent chip with a red dot. */
	.status-badge {
		display: inline-flex;
		align-items: center;
		gap: 6px;
		flex-shrink: 0;
		height: 24px;
		padding: 0 10px;
		border-radius: 999px;
		background: rgba(0, 0, 0, 0.18);
		color: rgba(255, 255, 255, 0.92);
		font-size: 0.78rem;
		font-weight: 600;
	}

	.status-dot {
		width: 7px;
		height: 7px;
		border-radius: 50%;
		background: #ff5a5f;
	}

	/* Right-side cluster (collaborators / avatar / present / share / link). */
	.right-cluster {
		display: flex;
		align-items: center;
		gap: 0.5rem;
		flex-shrink: 0;
	}

	.hbtn {
		width: 32px;
		height: 32px;
		display: inline-flex;
		align-items: center;
		justify-content: center;
		background: transparent;
		border: none;
		border-radius: 7px;
		color: rgba(255, 255, 255, 0.92);
		cursor: pointer;
		transition: background 0.12s ease;
	}

	.hbtn:hover {
		background: rgba(255, 255, 255, 0.16);
	}

	.hbtn svg {
		width: 19px;
		height: 19px;
	}

	.share-btn {
		display: inline-flex;
		align-items: center;
		gap: 7px;
		height: 34px;
		padding: 0 16px;
		background: #a6192e;
		color: #ffffff;
		border: none;
		border-radius: 8px;
		font-family: inherit;
		font-size: 0.88rem;
		font-weight: 600;
		cursor: pointer;
		transition: background 0.12s ease;
	}

	.share-btn:hover {
		background: #c01933;
	}

	.share-btn svg {
		width: 16px;
		height: 16px;
	}

	.file-name:hover {
		background: rgba(255, 255, 255, 0.08);
	}

	.file-name:focus {
		outline: none;
		background: rgba(255, 255, 255, 0.15);
		border-color: rgba(255, 255, 255, 0.4);
	}

	.menu-wrapper {
		position: relative;
	}

	.menu-trigger {
		background: transparent;
		border: none;
		color: white;
		padding: 0.4rem 0.7rem;
		font-size: 0.9rem;
		cursor: pointer;
		border-radius: 4px;
		font-family: inherit;
		transition: background 0.15s ease;
	}

	.menu-trigger:hover,
	.menu-trigger.active {
		background: rgba(255, 255, 255, 0.18);
	}

	.menu-trigger:focus-visible {
		outline: 2px solid rgba(255, 255, 255, 0.6);
		outline-offset: 1px;
	}

	.dropdown {
		position: absolute;
		top: calc(100% + 6px);
		left: 0;
		min-width: 240px;
		background: #ffffff;
		color: #2a2a2a;
		border: 1px solid #ebe5d8;
		border-radius: 10px;
		box-shadow: 0 12px 28px rgba(0, 0, 0, 0.12);
		padding: 6px;
		z-index: 50;
		display: flex;
		flex-direction: column;
		gap: 1px;
	}

	.submenu {
		top: -6px;
		left: calc(100% + 4px);
		min-width: 180px;
	}

	.item-wrapper {
		position: relative;
		display: flex;
		flex-direction: column;
	}

	.dropdown-item {
		display: flex;
		align-items: center;
		gap: 12px;
		background: transparent;
		border: none;
		color: #2a2a2a;
		font-family: inherit;
		font-size: 0.875rem;
		padding: 8px 12px;
		text-align: left;
		cursor: pointer;
		border-radius: 6px;
		width: 100%;
		transition:
			background 0.1s ease,
			color 0.1s ease;
	}

	.dropdown-item:hover:not(:disabled),
	.dropdown-item.active:not(:disabled) {
		background: #fbeef0;
		color: #76232f;
	}

	.dropdown-item:disabled {
		color: #b8b8b8;
		cursor: not-allowed;
	}

	.dropdown-item.danger {
		color: #b42318;
	}

	.dropdown-item.danger:hover:not(:disabled) {
		background: #fdf2f1;
		color: #b42318;
	}

	.item-icon-wrap {
		width: 18px;
		height: 18px;
		flex-shrink: 0;
		display: inline-flex;
		align-items: center;
		justify-content: center;
		color: #5a5c58;
	}

	.dropdown-item:hover:not(:disabled) .item-icon-wrap,
	.dropdown-item.active:not(:disabled) .item-icon-wrap {
		color: #76232f;
	}

	.dropdown-item.danger .item-icon-wrap {
		color: #b42318;
	}

	.dropdown-item:disabled .item-icon-wrap {
		color: #c8c8c8;
	}

	.item-icon {
		width: 16px;
		height: 16px;
	}

	.item-label {
		flex: 1;
	}

	.item-shortcut {
		font-size: 0.78rem;
		color: #8a8b83;
		font-variant-numeric: tabular-nums;
	}

	.dropdown-item:hover:not(:disabled) .item-shortcut,
	.dropdown-item.active:not(:disabled) .item-shortcut {
		color: #a6192e;
	}

	.item-chevron {
		display: inline-flex;
		width: 14px;
		height: 14px;
		color: #8a8b83;
	}

	.item-chevron .item-icon {
		width: 14px;
		height: 14px;
	}

	.dropdown-divider {
		height: 1px;
		background: #e8e5de;
		margin: 4px 4px;
	}

	.avatar {
		width: 30px;
		height: 30px;
		flex-shrink: 0;
		border-radius: 50%;
		background: #c01933;
		color: white;
		display: flex;
		align-items: center;
		justify-content: center;
		font-weight: 700;
		font-size: 0.75rem;
		letter-spacing: 0.02em;
	}
</style>

// client/src/lib/components/MenuBar.tsx
'use client';

import { useCallback, useEffect, useState } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { ChevronDown, Download, LayoutGrid, Settings as SettingsIcon, LogOut } from 'lucide-react';
import UiIcon from '@/lib/components/icons/UiIcon';
import KeyboardShortcutsModal from '@/lib/components/KeyboardShortcutsModal';
import { useEditor } from '@/lib/flow/EditorContext';
import { useEditorMeta, type DiagramStatus } from '@/lib/stores/editor-meta.store';
import { useVisibleUnsavedPageIds } from '@/lib/stores/editor-doc.store';
import { useAuthStore, accountInitials } from '@/lib/stores/auth.store';

interface MenuItem {
  type?: 'divider';
  icon?: string;
  label?: string;
  shortcut?: string;
  disabled?: boolean;
  danger?: boolean;
  toggle?: boolean;
  checked?: boolean;
  submenu?: MenuItem[];
  onClick?: () => void;
}

const DOCUMENT_STATUSES: { id: DiagramStatus; label: string; color: string }[] = [
  { id: 'draft', label: 'Draft', color: '#f97316' },
  { id: 'complete', label: 'Complete', color: '#22c55e' },
  { id: 'archived', label: 'Archived', color: '#9ca3af' },
];

const menuLabels = ['File', 'Edit', 'View', 'Arrange', 'Help'];
const QUICK_EXPORT_ORDER = ['png', 'jpeg', 'pdf', 'easydraw'];

export default function MenuBar() {
  const editor = useEditor();
  const router = useRouter();

  const fileName = useEditorMeta((s) => s.fileName);
  const setFileName = useEditorMeta((s) => s.setFileName);
  const status = useEditorMeta((s) => s.status);
  const setStatus = useEditorMeta((s) => s.setStatus);

  // The editor sits behind the auth guard so user is populated; fallbacks are
  // just defensive.
  const user = useAuthStore((s) => s.user);
  const logout = useAuthStore((s) => s.logout);
  const accountName = user?.name ?? user?.email ?? 'Account';
  const accountEmail = user?.email ?? '';
  const hasNameAndEmail = !!(user?.name && user?.email);
  const userInitials = accountInitials(user);

  // Canvas dirtiness gives immediate feedback before the debounce runs;
  // saveStatus keeps the spinner alive through the debounce + PATCH.
  const unsavedPageIds = useVisibleUnsavedPageIds();
  const saving = editor.state.saveStatus === 'saving' || unsavedPageIds.length > 0;
  const saveFailed = editor.state.saveStatus === 'error';
  const currentDocumentStatus =
    DOCUMENT_STATUSES.find((s) => s.id === status) ?? DOCUMENT_STATUSES[0];

  const [openMenu, setOpenMenu] = useState<string | null>(null);
  const [openSubmenu, setOpenSubmenu] = useState<string | null>(null);
  const [statusMenuOpen, setStatusMenuOpen] = useState(false);
  const [userMenuOpen, setUserMenuOpen] = useState(false);
  const [quickExportOpen, setQuickExportOpen] = useState(false);
  const [shortcutsOpen, setShortcutsOpen] = useState(false);

  const closeMenus = useCallback(() => {
    setOpenMenu(null);
    setOpenSubmenu(null);
    setStatusMenuOpen(false);
    setUserMenuOpen(false);
    setQuickExportOpen(false);
  }, []);

  const toggleMenu = (label: string) => {
    setOpenMenu((prev) => (prev === label ? null : label));
    setOpenSubmenu(null);
    setStatusMenuOpen(false);
    setUserMenuOpen(false);
    setQuickExportOpen(false);
  };

  const toggleStatusMenu = () => {
    setOpenMenu(null);
    setOpenSubmenu(null);
    setStatusMenuOpen((v) => !v);
    setUserMenuOpen(false);
    setQuickExportOpen(false);
  };

  const toggleUserMenu = () => {
    setOpenMenu(null);
    setOpenSubmenu(null);
    setStatusMenuOpen(false);
    setUserMenuOpen((v) => !v);
    setQuickExportOpen(false);
  };

  const toggleQuickExport = () => {
    setOpenMenu(null);
    setOpenSubmenu(null);
    setStatusMenuOpen(false);
    setUserMenuOpen(false);
    setQuickExportOpen((v) => !v);
  };

  const selectStatus = (next: DiagramStatus) => {
    setStatus(next);
    setStatusMenuOpen(false);
  };

  const runItem = (item: MenuItem) => {
    if (item.disabled) return;
    if (item.submenu) {
      setOpenSubmenu((prev) => (prev === item.label ? null : (item.label ?? null)));
      return;
    }
    if (!item.onClick) return;
    item.onClick();
    closeMenus();
  };

  const runQuickExport = (formatId: string) => {
    setQuickExportOpen(false);
    editor.exportAs(formatId);
  };

  const goToDashboard = () => {
    setUserMenuOpen(false);
    router.push('/dashboard');
  };

  const goToSettings = () => {
    setUserMenuOpen(false);
    router.push('/settings');
  };

  const signOut = async () => {
    setUserMenuOpen(false);
    await logout();
    router.push('/login');
  };

  // Outside click + Escape close any open dropdown / submenu.
  useEffect(() => {
    const onPointer = (event: PointerEvent) => {
      const target = event.target as HTMLElement | null;
      // `data-*-root` DOM hooks survive the Tailwind migration — don't key this
      // on a styling class, those get renamed.
      if (
        target?.closest(
          '[data-menu-root], [data-status-root], [data-user-root], [data-quick-export-root]',
        )
      )
        return;
      closeMenus();
    };
    const onKey = (event: KeyboardEvent) => {
      if (event.key === 'Escape') closeMenus();
    };
    window.addEventListener('pointerdown', onPointer);
    window.addEventListener('keydown', onKey);
    return () => {
      window.removeEventListener('pointerdown', onPointer);
      window.removeEventListener('keydown', onKey);
    };
  }, [closeMenus]);

  // Export submenu built off the registry so new formats appear automatically.
  const exportSubmenu: MenuItem[] = editor.exportFormats.map((format) => ({
    label: `${format.label} (${format.extension})`,
    onClick: () => editor.exportAs(format.id),
  }));

  const quickExportFormats = editor.exportFormats
    .filter((format) => QUICK_EXPORT_ORDER.includes(format.id))
    .sort((a, b) => QUICK_EXPORT_ORDER.indexOf(a.id) - QUICK_EXPORT_ORDER.indexOf(b.id));

  // Rebuilt each render so disabled/checked state stays in sync with state/history.
  const menus: Record<string, MenuItem[]> = {
    File: [
      { icon: 'new', label: 'New', shortcut: 'Ctrl+N', onClick: editor.newFile },
      { icon: 'open', label: 'Open…', shortcut: 'Ctrl+O', onClick: editor.open },
      { icon: 'save', label: 'Save', shortcut: 'Ctrl+S', onClick: editor.save },
      { icon: 'save-as', label: 'Save As…', shortcut: 'Ctrl+Shift+S', onClick: editor.saveAs },
      { type: 'divider' },
      { icon: 'export', label: 'Export as', submenu: exportSubmenu },
    ],
    Edit: [
      {
        icon: 'undo',
        label: 'Undo',
        shortcut: 'Ctrl+Z',
        onClick: editor.undo,
        disabled: !editor.history.canUndo,
      },
      {
        icon: 'redo',
        label: 'Redo',
        shortcut: 'Ctrl+Y',
        onClick: editor.redo,
        disabled: !editor.history.canRedo,
      },
      { type: 'divider' },
      { icon: 'cut', label: 'Cut', shortcut: 'Ctrl+X', onClick: editor.cut },
      { icon: 'copy', label: 'Copy', shortcut: 'Ctrl+C', onClick: editor.copy },
      { icon: 'paste', label: 'Paste', shortcut: 'Ctrl+V', onClick: editor.paste },
      { icon: 'duplicate', label: 'Duplicate', shortcut: 'Ctrl+D', onClick: editor.duplicate },
      { type: 'divider' },
      { icon: 'select-all', label: 'Select all', shortcut: 'Ctrl+A', onClick: editor.selectAll },
      { type: 'divider' },
      {
        icon: 'delete',
        label: 'Delete',
        shortcut: 'Del',
        onClick: editor.deleteSelected,
        danger: true,
      },
    ],
    View: [
      {
        toggle: true,
        label: 'Show grid',
        checked: editor.state.showGrid,
        onClick: editor.toggleShowGrid,
      },
      {
        toggle: true,
        label: 'Snap to grid',
        checked: editor.state.snapToGrid,
        onClick: editor.toggleSnapToGrid,
      },
      { type: 'divider' },
      { icon: 'zoom-in', label: 'Zoom in', shortcut: 'Ctrl+=', onClick: editor.zoomIn },
      { icon: 'zoom-out', label: 'Zoom out', shortcut: 'Ctrl+-', onClick: editor.zoomOut },
      { icon: 'fit', label: 'Fit to screen', shortcut: 'Ctrl+Shift+H', onClick: editor.fitView },
    ],
    Arrange: [
      {
        icon: 'bring-front',
        label: 'Bring to front',
        shortcut: 'Ctrl+Shift+F',
        onClick: editor.bringToFront,
      },
      {
        icon: 'send-back',
        label: 'Send to back',
        shortcut: 'Ctrl+Shift+B',
        onClick: editor.sendToBack,
      },
      { type: 'divider' },
      { icon: 'group', label: 'Group', shortcut: 'Ctrl+G', onClick: editor.group },
      { icon: 'ungroup', label: 'Ungroup', shortcut: 'Ctrl+Shift+G', onClick: editor.ungroup },
    ],
    Help: [
      {
        icon: 'info',
        label: 'About EasyDraw',
        // Open the public landing; the user stays logged in.
        onClick: () => router.push('/'),
      },
      {
        icon: 'keyboard',
        label: 'Keyboard shortcuts',
        shortcut: 'Ctrl+/',
        onClick: () => setShortcutsOpen(true),
      },
    ],
  };

  return (
    <>
      <header
        className="flex h-[52px] items-center gap-[0.4rem] bg-mq-maroon px-[0.85rem] text-white
          [font-family:system-ui,-apple-system,sans-serif]"
      >
        <Link
          href="/dashboard"
          title="Back to dashboard"
          aria-label="Back to dashboard"
          className="flex flex-shrink-0 items-center rounded-md p-1 transition-colors hover:bg-white/10"
        >
          <svg width="40" height="40" viewBox="0 0 48 48" fill="none" aria-hidden="true">
            <rect x="4" y="4" width="40" height="40" rx="8" fill="#A6192E" />
            <rect x="12" y="12" width="12" height="8" rx="2" fill="white" opacity="0.95" />
            <rect x="28" y="28" width="12" height="8" rx="2" fill="white" opacity="0.95" />
            <path
              d="M24 16 L28 16 L28 32"
              stroke="white"
              strokeWidth="2"
              strokeLinecap="round"
              opacity="0.8"
            />
          </svg>
        </Link>

        <input
          className="min-w-[6rem] max-w-[18rem] rounded-[6px] border border-transparent bg-transparent
            px-2 py-1 text-[0.95rem] font-bold text-white transition-colors duration-150
            hover:bg-white/[0.08] focus:border-white/40 focus:bg-white/[0.15] focus:outline-none"
          value={fileName}
          onChange={(e) => setFileName(e.target.value)}
          aria-label="Document file name"
          placeholder="Untitled"
        />

        <div className="relative flex-shrink-0" data-status-root>
          <button
            type="button"
            className="inline-flex h-6 cursor-pointer items-center gap-1.5 rounded-full border-none
              bg-black/[0.18] px-2.5 text-[0.78rem] font-semibold text-white/[0.92]
              transition-colors duration-150 hover:bg-white/[0.18]
              focus-visible:outline-offset-1 focus-visible:[outline:2px_solid_rgba(255,255,255,0.6)]"
            aria-label="Document status"
            aria-haspopup="menu"
            aria-expanded={statusMenuOpen}
            onClick={toggleStatusMenu}
          >
            <span
              className="h-[7px] w-[7px] rounded-full"
              style={{ backgroundColor: currentDocumentStatus.color }}
            />
            <span>{currentDocumentStatus.label}</span>
          </button>

          {statusMenuOpen && (
            <div
              className="absolute top-[calc(100%+10px)] left-1/2 z-50 flex w-[220px] -translate-x-1/2
                flex-col gap-px rounded-[10px] border border-line-dropdown bg-white p-1.5
                text-[#2a2a2a] shadow-[0_12px_28px_rgba(0,0,0,0.12)]"
              role="menu"
              aria-label="Document status"
            >
              <span
                className="absolute top-[-6px] left-1/2 h-3 w-3 -translate-x-1/2 rotate-45
                  border-t border-l border-line-dropdown bg-white"
                aria-hidden="true"
              />
              {DOCUMENT_STATUSES.map((s) => (
                <button
                  key={s.id}
                  type="button"
                  role="menuitemradio"
                  aria-checked={status === s.id}
                  className={`group relative flex w-full cursor-pointer items-center gap-3 rounded-md
                    border-none bg-transparent px-3 py-2 text-left text-[0.875rem] text-[#2a2a2a]
                    transition-colors duration-100 enabled:hover:bg-mq-pink enabled:hover:text-mq-maroon
                    [&.active]:bg-mq-pink [&.active]:text-mq-maroon ${status === s.id ? 'active' : ''}`}
                  onClick={() => selectStatus(s.id)}
                >
                  <span
                    className="h-[9px] w-[9px] flex-shrink-0 rounded-full"
                    style={{ backgroundColor: s.color }}
                  />
                  <span className="flex-1">{s.label}</span>
                </button>
              ))}
            </div>
          )}
        </div>

        <nav className="ml-2 flex gap-[0.1rem]" data-menu-root>
          {menuLabels.map((label) => (
            <div key={label} className="relative">
              <button
                className={`cursor-pointer rounded-[4px] border-none bg-transparent px-[0.7rem]
                  py-[0.4rem] text-[0.9rem] text-white transition-colors duration-150
                  hover:bg-white/[0.18]
                  focus-visible:outline-offset-1 focus-visible:[outline:2px_solid_rgba(255,255,255,0.6)]
                  [&.active]:bg-white/[0.18] ${openMenu === label ? 'active' : ''}`}
                type="button"
                aria-haspopup="menu"
                aria-expanded={openMenu === label}
                onClick={() => toggleMenu(label)}
              >
                {label}
              </button>
              {openMenu === label && (
                <div
                  className="absolute top-[calc(100%+6px)] left-0 z-50 flex min-w-[240px] flex-col
                    gap-px rounded-[10px] border border-line-dropdown bg-white p-1.5 text-[#2a2a2a]
                    shadow-[0_12px_28px_rgba(0,0,0,0.12)]"
                  role="menu"
                >
                  {menus[label].map((item, i) =>
                    item.type === 'divider' ? (
                      <div key={`d${i}`} className="mx-1 my-1 h-px bg-[#e8e5de]" role="separator" />
                    ) : (
                      <div key={item.label} className="relative flex flex-col">
                        <button
                          type="button"
                          role="menuitem"
                          className={`group flex w-full cursor-pointer items-center gap-3 rounded-md
                            border-none bg-transparent px-3 py-2 text-left text-[0.875rem] text-[#2a2a2a]
                            transition-colors duration-100 enabled:hover:bg-mq-pink enabled:hover:text-mq-maroon
                            disabled:cursor-not-allowed disabled:text-[#b8b8b8]
                            [&.active:not(:disabled)]:bg-mq-pink [&.active:not(:disabled)]:text-mq-maroon
                            [&.danger]:text-[#b42318]
                            [&.danger:not(:disabled)]:hover:bg-[#fdf2f1]
                            [&.danger:not(:disabled)]:hover:text-[#b42318]
                            ${item.danger ? 'danger' : ''}
                            ${item.submenu && openSubmenu === item.label ? 'active' : ''}`}
                          disabled={item.disabled}
                          onClick={() => runItem(item)}
                        >
                          <span
                            className="inline-flex h-[18px] w-[18px] flex-shrink-0 items-center
                              justify-center text-[#5a5c58]
                              group-[:hover:not(:disabled)]:text-mq-maroon
                              group-[.active:not(:disabled)]:text-mq-maroon
                              group-[.danger]:text-[#b42318] group-disabled:text-[#c8c8c8]"
                          >
                            {item.toggle
                              ? item.checked && <UiIcon name="check" className="h-4 w-4" />
                              : item.icon && <UiIcon name={item.icon} className="h-4 w-4" />}
                          </span>
                          <span className="flex-1">{item.label}</span>
                          {item.shortcut ? (
                            <span
                              className="text-[0.78rem] tabular-nums text-ink-muted
                                group-[:hover:not(:disabled)]:text-mq-red
                                group-[.active:not(:disabled)]:text-mq-red"
                            >
                              {item.shortcut}
                            </span>
                          ) : (
                            item.submenu && (
                              <span className="inline-flex h-3.5 w-3.5 text-ink-muted [&_svg]:size-3.5">
                                <UiIcon name="chevron-right" className="h-4 w-4" />
                              </span>
                            )
                          )}
                        </button>
                        {item.submenu && openSubmenu === item.label && (
                          <div
                            className="absolute top-[-6px] left-[calc(100%+4px)] z-50 flex min-w-[180px]
                              flex-col gap-px rounded-[10px] border border-line-dropdown bg-white p-1.5
                              text-[#2a2a2a] shadow-[0_12px_28px_rgba(0,0,0,0.12)]"
                            role="menu"
                          >
                            {item.submenu.map((sub) => (
                              <button
                                key={sub.label}
                                type="button"
                                role="menuitem"
                                className="group flex w-full cursor-pointer items-center gap-3 rounded-md
                                  border-none bg-transparent px-3 py-2 text-left text-[0.875rem]
                                  text-[#2a2a2a] transition-colors duration-100
                                  enabled:hover:bg-mq-pink enabled:hover:text-mq-maroon
                                  disabled:cursor-not-allowed disabled:text-[#b8b8b8]"
                                disabled={sub.disabled}
                                onClick={() => runItem(sub)}
                              >
                                <span className="inline-flex h-[18px] w-[18px] flex-shrink-0" />
                                <span className="flex-1">{sub.label}</span>
                                {sub.shortcut && (
                                  <span
                                    className="text-[0.78rem] tabular-nums text-ink-muted
                                      group-[:hover:not(:disabled)]:text-mq-red"
                                  >
                                    {sub.shortcut}
                                  </span>
                                )}
                              </button>
                            ))}
                          </div>
                        )}
                      </div>
                    ),
                  )}
                </div>
              )}
            </div>
          ))}
        </nav>

        <div className="flex-auto" />

        <div className="flex flex-shrink-0 items-center gap-2">
          {/* Save status follows the debounced PATCH lifecycle. Click to force a
              save or retry after an error. */}
          <button
            type="button"
            className="mb-tip relative inline-flex h-8 w-8 cursor-pointer items-center justify-center
              rounded-[7px] border-none bg-transparent text-white/[0.92] transition-colors
              duration-[120ms] hover:bg-white/[0.16]"
            aria-label={saving ? 'Saving…' : saveFailed ? 'Save failed. Click to retry' : 'Saved'}
            onClick={editor.save}
          >
            {saving ? (
              <svg
                viewBox="0 0 24 24"
                className="h-[18px] w-[18px] animate-spin"
                fill="none"
                stroke="currentColor"
                strokeWidth="1.8"
                strokeLinecap="round"
                strokeLinejoin="round"
              >
                <path d="M23 4v6h-6" />
                <path d="M1 20v-6h6" />
                <path d="M3.51 9a9 9 0 0 1 14.85-3.36L23 10" />
                <path d="M1 14l4.64 4.36A9 9 0 0 0 20.49 15" />
              </svg>
            ) : saveFailed ? (
              <svg
                viewBox="0 0 24 24"
                className="h-[18px] w-[18px] text-red-200"
                fill="none"
                stroke="currentColor"
                strokeWidth="1.7"
                strokeLinecap="round"
                strokeLinejoin="round"
              >
                <path d="M17.5 19a4.5 4.5 0 1 0 0-9h-1.8A7 7 0 1 0 4 15.3" />
                <path d="m9.5 12 5 5" />
                <path d="m14.5 12-5 5" />
              </svg>
            ) : (
              <svg
                viewBox="0 0 24 24"
                className="h-[18px] w-[18px]"
                fill="none"
                stroke="currentColor"
                strokeWidth="1.7"
                strokeLinecap="round"
                strokeLinejoin="round"
              >
                <path d="M17.5 19a4.5 4.5 0 1 0 0-9h-1.8A7 7 0 1 0 4 15.3" />
                <path d="m8.5 13.5 2.5 2.5 4.5-4.5" />
              </svg>
            )}
          </button>

          <div className="relative flex-shrink-0" data-user-root>
            <button
              type="button"
              className="flex h-[30px] w-[30px] cursor-pointer items-center justify-center rounded-full
                border-none bg-mq-red-hover text-[0.75rem] font-bold tracking-[0.02em] text-white
                transition-colors duration-[120ms] hover:bg-mq-maroon
                focus-visible:outline-offset-1 focus-visible:[outline:2px_solid_rgba(255,255,255,0.6)]"
              title={accountName}
              aria-haspopup="menu"
              aria-expanded={userMenuOpen}
              onClick={toggleUserMenu}
            >
              {userInitials}
            </button>

            {userMenuOpen && (
              <div
                className="absolute top-[calc(100%+8px)] right-0 z-50 flex w-56 flex-col rounded-[10px]
                  border border-line-dropdown bg-white p-1.5 text-[#2a2a2a]
                  shadow-[0_12px_28px_rgba(0,0,0,0.14)]"
                role="menu"
                aria-label="Account"
              >
                <div className="px-2.5 py-1.5">
                  <p className="text-[0.72rem] text-ink-muted">Signed in as</p>
                  <p className="truncate text-[0.875rem] font-medium text-[#2a2a2a]">{accountName}</p>
                  {hasNameAndEmail && (
                    <p className="truncate text-[0.72rem] text-ink-muted">{accountEmail}</p>
                  )}
                </div>

                <div className="mx-1 my-1 h-px bg-[#e8e5de]" role="separator" />

                <button
                  type="button"
                  role="menuitem"
                  className="group flex w-full cursor-pointer items-center gap-2.5 rounded-md
                    border-none bg-transparent px-2.5 py-2 text-left text-[0.875rem] text-[#2a2a2a]
                    transition-colors duration-100 enabled:hover:bg-mq-pink enabled:hover:text-mq-maroon"
                  onClick={goToDashboard}
                >
                  <LayoutGrid size={15} className="flex-shrink-0 text-[#5a5c58] group-hover:text-mq-maroon" />
                  My diagrams
                </button>
                <button
                  type="button"
                  role="menuitem"
                  className="group flex w-full cursor-pointer items-center gap-2.5 rounded-md
                    border-none bg-transparent px-2.5 py-2 text-left text-[0.875rem] text-[#2a2a2a]
                    transition-colors duration-100 enabled:hover:bg-mq-pink enabled:hover:text-mq-maroon"
                  onClick={goToSettings}
                >
                  <SettingsIcon size={15} className="flex-shrink-0 text-[#5a5c58] group-hover:text-mq-maroon" />
                  Settings
                </button>
                <button
                  type="button"
                  role="menuitem"
                  className="group flex w-full cursor-pointer items-center gap-2.5 rounded-md
                    border-none bg-transparent px-2.5 py-2 text-left text-[0.875rem] text-[#2a2a2a]
                    transition-colors duration-100 enabled:hover:bg-mq-pink enabled:hover:text-mq-maroon"
                  onClick={signOut}
                >
                  <LogOut size={15} className="flex-shrink-0 text-[#5a5c58] group-hover:text-mq-maroon" />
                  Sign out
                </button>
              </div>
            )}
          </div>

          <button
            type="button"
            className="inline-flex h-9 cursor-pointer items-center justify-center gap-2 rounded-[8px]
              border-none bg-mq-red px-[18px] text-[0.95rem] font-semibold text-white transition-colors
              duration-[120ms] hover:bg-mq-red-hover"
            onClick={editor.present}
          >
            <svg
              viewBox="0 0 24 24"
              className="h-[19px] w-[19px]"
              fill="none"
              stroke="currentColor"
              strokeWidth="1.8"
              strokeLinecap="round"
              strokeLinejoin="round"
            >
              <path d="M8 5v14l11-7z" />
            </svg>
            Present
          </button>

          <div className="relative flex-shrink-0" data-quick-export-root>
            <button
              type="button"
              className="inline-flex h-9 cursor-pointer items-center justify-center gap-1.5 rounded-[8px]
                border border-white/25 bg-white/10 px-3 text-[0.9rem] font-semibold text-white
                transition-colors duration-[120ms] hover:bg-white/[0.18]"
              aria-label="Export diagram"
              aria-haspopup="menu"
              aria-expanded={quickExportOpen}
              onClick={toggleQuickExport}
            >
              <Download size={17} />
              Export
              <ChevronDown
                size={14}
                className={`transition-transform duration-150 ${quickExportOpen ? 'rotate-180' : ''}`}
              />
            </button>

            {quickExportOpen && (
              <div
                className="absolute top-[calc(100%+8px)] right-0 z-50 flex min-w-[180px] flex-col
                  gap-px rounded-[10px] border border-line-dropdown bg-white p-1.5 text-[#2a2a2a]
                  shadow-[0_12px_28px_rgba(0,0,0,0.14)]"
                role="menu"
                aria-label="Export diagram"
              >
                {quickExportFormats.map((format) => (
                  <button
                    key={format.id}
                    type="button"
                    role="menuitem"
                    className="group flex w-full cursor-pointer items-center gap-3 rounded-md
                      border-none bg-transparent px-3 py-2 text-left text-[0.875rem] text-[#2a2a2a]
                      transition-colors duration-100 enabled:hover:bg-mq-pink enabled:hover:text-mq-maroon"
                    onClick={() => runQuickExport(format.id)}
                  >
                    <Download size={15} className="flex-shrink-0 text-[#5a5c58] group-hover:text-mq-maroon" />
                    <span className="flex-1">{format.label}</span>
                    <span className="text-[0.75rem] text-ink-muted">{format.extension}</span>
                  </button>
                ))}
              </div>
            )}
          </div>
        </div>
      </header>

      <KeyboardShortcutsModal open={shortcutsOpen} onClose={() => setShortcutsOpen(false)} />
    </>
  );
}
